from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_XLSX = ROOT / "data" / "chest_pain_ddx_workflow_v1_2.xlsx"
CHECKLIST_XLSX = ROOT / "data" / "chest_pain_differential_checklist_from_v1_2.xlsx"


CODE_BY_NO: dict[int, str] = {
    1: "STEMI",
    2: "NSTEMI",
    3: "UA",
    4: "SA_CCD",
    5: "VSA",
    6: "INOCA",
    7: "SCAD",
    8: "DIS",
    9: "TAA",
    10: "PERI",
    11: "MYO",
    12: "AHF",
    13: "AS",
    14: "MVP",
    15: "HCM",
    16: "ARR",
    17: "TTS",
    18: "HTN_EMERG",
    19: "PE",
    20: "TPTX",
    21: "PTX",
    22: "TRAUMATIC_PTX_HEMOTHORAX",
    23: "PNA",
    24: "PLEUR",
    25: "PLEFF",
    26: "PULM_INFARCT",
    27: "PMED",
    28: "ASTHMA_EXAC",
    29: "COPD_EXAC",
    30: "LUNGCA",
    31: "GERD",
    32: "ESOPH",
    33: "ESPASM",
    34: "BOER",
    35: "MALLORY_WEISS",
    36: "PUD",
    37: "DYSPEP",
    38: "BILCOL",
    39: "CHOLE",
    40: "CHOLANG",
    41: "PANC",
    42: "HH",
    43: "COSTO",
    44: "TIETZE",
    45: "STRAIN",
    46: "RIB",
    47: "CHEST_CONTUSION",
    48: "ICN",
    49: "CRAD_TRAD",
    50: "ZOSTER",
    51: "FIBRO",
    52: "TOS",
    53: "PANIC",
    54: "ANX",
    55: "HVS",
    56: "FCP",
    57: "SOMATIC_CHEST_PAIN",
    58: "T2MI",
    59: "AAS_IMH_PAU",
    60: "CORONARY_EMBOLISM",
    61: "STIMULANT_ISCHEMIA",
    62: "MINOCA",
    63: "TAMPONADE",
    64: "PH_RV_ISCHEMIA",
    65: "ANOMALOUS_CORONARY",
    66: "EMP",
    67: "VIRAL_PLEURITIS",
    68: "TB_PLEURITIS",
    69: "SICKLE_ACUTE_CHEST",
    70: "VIRAL_PNA",
    71: "LUNG_ABSCESS",
    72: "MEDIASTINITIS",
    73: "PERF_PUD",
    74: "ACHALASIA",
    75: "PILL_INFECTIOUS_EOE_ESOPHAGITIS",
    76: "ESOPHAGEAL_CANCER",
    77: "GASTRIC_VOLVULUS",
    78: "SPLENIC_INFARCT",
    79: "SUBPHRENIC_ABSCESS",
    80: "THORACIC_COMPRESSION_FX",
    81: "SLIPPING_RIB",
    82: "SC_JOINT_INFECTION",
    83: "XIPHO",
    84: "PRECORDIAL_CATCH",
    85: "AUTOIMMUNE_SEROSITIS",
    86: "CO_POISONING_ISCHEMIA",
    87: "MASTITIS_MONDOR",
    88: "TRAUMATIC_AORTIC_INJURY",
    89: "PULM_CONTUSION_FLAIL",
    90: "STRANGULATED_HERNIA",
}


DIAGNOSIS_CATEGORY_MAP = {
    "심혈관": "cardiac",
    "심혈관/독성": "cardiac",
    "독성/심혈관": "cardiac",
    "심혈관/폐혈관": "cardiac",
    "폐/흉막": "pulmonary_pleural",
    "폐/감염": "pulmonary_pleural",
    "혈액/폐": "pulmonary_pleural",
    "감염/종격동": "pulmonary_pleural",
    "외상/폐": "pulmonary_pleural",
    "위장관": "gastrointestinal",
    "위장관/외과": "gastrointestinal",
    "식도": "gastrointestinal",
    "식도/종양": "gastrointestinal",
    "복부혈관/혈액": "gastrointestinal",
    "복부감염": "gastrointestinal",
    "근골격/신경": "musculoskeletal_neuro_skin",
    "근골격/신경/혈관": "musculoskeletal_neuro_skin",
    "근골격/척추": "musculoskeletal_neuro_skin",
    "근골격": "musculoskeletal_neuro_skin",
    "근골격/감염": "musculoskeletal_neuro_skin",
    "근골격/기능": "musculoskeletal_neuro_skin",
    "흉벽/유방": "musculoskeletal_neuro_skin",
    "외상/혈관": "aortic",
    "류마티스/흉막/심낭": "pulmonary_pleural",
    "정신/기능성": "psychiatric_functional",
    "정신/기능성/식도": "psychiatric_functional",
}

CHECKLIST_CATEGORY_MAP = {
    "활력/즉시위험": "vital",
    "문진/증상": "history",
    "위험인자/과거력": "history",
    "신체진찰": "physical",
    "ECG/혈액/검사": "lab",
    "영상/시술/확진": "thoracic_imaging",
    "Score/기준": "history",
    "위장관/식도": "gi_test",
    "근골격/신경/흉벽": "msk_neuro_skin",
    "정신/기능": "psych_functional",
    "기타": "history",
}


HEADER = """// Generated by scripts/importClinicalXlsx.py from chest pain v1.2 workbooks.
// Do not edit generated arrays by hand; update the source workbook or generator instead.
"""


def clean(value: Any) -> str:
    if pd.isna(value):
        return ""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def compact(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def split_cell(value: str) -> list[str]:
    value = clean(value)
    if not value:
        return []
    parts = re.split(r";|\n|---", value)
    return [compact(part) for part in parts if compact(part)]


def first_sentences(*values: str, limit: int = 2) -> list[str]:
    text = " ".join(compact(value) for value in values if compact(value))
    if not text:
        return []
    parts = re.split(r"(?<=[.!?。])\s+|(?<=다\.)\s+", text)
    return [part.strip() for part in parts if part.strip()][:limit]


def to_ts(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def priority_to_urgency(priority: str) -> str:
    text = priority.lower()
    if "immediate" in text:
        return "emergent"
    if "high" in text:
        return "urgent"
    return "routine"


def is_must_not_miss(no: int, priority: str, gate: str, red_flag_nos: set[int]) -> bool:
    gate_text = gate or ""
    if no in red_flag_nos:
        return True
    if "Immediate life threat" in priority:
        return True
    return any(
        token in gate_text
        for token in [
            "항상 자동 게이트",
            "자동 게이트:",
            "쇼크",
            "저혈압",
            "패혈증",
            "파열",
            "압전",
            "긴장성",
        ]
    )


def diagnosis_category(original: str, no: int) -> str:
    if no in {8, 9, 59, 88}:
        return "aortic"
    return DIAGNOSIS_CATEGORY_MAP.get(original, "history").replace("history", "cardiac")


def checklist_category(section: str, label: str, source_column: str) -> str:
    if section == "영상/시술/확진":
        text = f"{label} {source_column}".lower()
        if any(token in text for token in ["echo", "cmr", "관상", "심초음파", "cardiac"]):
            return "cardiac_imaging"
        if any(token in text for token in ["egd", "식도", "pH", "hrm", "ruq", "복부", "담", "췌장"]):
            return "gi_test"
        return "thoracic_imaging"
    if section == "ECG/혈액/검사":
        if "ecg" in label.lower() or "st " in label.lower() or "st상승" in label.lower():
            return "ecg"
        return "lab"
    return CHECKLIST_CATEGORY_MAP.get(section, "history")


def source_urls(value: str) -> list[str]:
    return split_cell(value)


def status_to_state(value: str) -> str:
    return {
        "미확인": "unknown",
        "있음": "present",
        "없음": "absent",
        "해당없음": "unknown",
    }.get(clean(value), "unknown")


def rows_to_records(df: pd.DataFrame) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for _, row in df.iterrows():
        if row.isna().all():
            continue
        records.append({str(col): clean(row[col]) for col in df.columns})
    return records


def ids_from_cell(value: str, prefix: str) -> list[str]:
    return re.findall(rf"{prefix}-\d{{3,4}}", value or "")


def main() -> None:
    master = pd.read_excel(WORKFLOW_XLSX, sheet_name="01_DDx_Master")
    sources = pd.read_excel(WORKFLOW_XLSX, sheet_name="02_Sources")
    impl_rules = pd.read_excel(WORKFLOW_XLSX, sheet_name="03_Implementation_Rules")
    disposition = pd.read_excel(WORKFLOW_XLSX, sheet_name="04_Disposition")
    app_key = pd.read_excel(CHECKLIST_XLSX, sheet_name="01_AppKey_Checklist")
    comprehensive = pd.read_excel(CHECKLIST_XLSX, sheet_name="02_Comprehensive_Checklist")
    coverage = pd.read_excel(CHECKLIST_XLSX, sheet_name="03_DDx_Coverage")
    verbatim = pd.read_excel(CHECKLIST_XLSX, sheet_name="04_Map_Verbatim")
    red_flags = pd.read_excel(CHECKLIST_XLSX, sheet_name="05_RedFlag_Gates")
    score_items = pd.read_excel(CHECKLIST_XLSX, sheet_name="06_Score_Items")
    validation = pd.read_excel(CHECKLIST_XLSX, sheet_name="11_Validation")

    expected = {
        "diagnoses": (len(master.dropna(how="all")), 90),
        "appKey": (len(app_key.dropna(how="all")), 262),
        "comprehensive": (len(comprehensive.dropna(how="all")), 1169),
        "redFlags": (len(red_flags.dropna(how="all")), 18),
        "scoreItems": (len(score_items.dropna(how="all")), 33),
    }
    for name, (actual, want) in expected.items():
        if actual != want:
            raise ValueError(f"{name} row count mismatch: {actual} != {want}")

    if set(CODE_BY_NO) != set(int(no) for no in master.iloc[:, 0]):
        raise ValueError("CODE_BY_NO must cover exactly the 90 DDx rows")

    red_flag_nos = {int(no) for no in red_flags.iloc[:, 0].dropna()}
    coverage_by_no = {
        int(row.iloc[0]): row
        for _, row in coverage.iterrows()
        if not row.isna().all()
    }

    diagnoses: list[dict[str, Any]] = []
    name_to_code: dict[str, str] = {}
    code_to_name: dict[str, str] = {}
    code_to_en: dict[str, str] = {}
    for _, row in master.iterrows():
        no = int(row.iloc[0])
        code = CODE_BY_NO[no]
        name_ko = clean(row.iloc[1])
        name_en = clean(row.iloc[2])
        original_category = clean(row.iloc[3])
        priority = clean(row.iloc[4])
        gate = clean(row.iloc[5])
        suspicion = clean(row.iloc[6])
        initial_tests = clean(row.iloc[7])
        rule_in = clean(row.iloc[8])
        rule_out = clean(row.iloc[9])
        pitfalls = clean(row.iloc[10])
        mimics = clean(row.iloc[11])
        app_keys = clean(row.iloc[12])
        urls = clean(row.iloc[13])
        evidence_level = clean(row.iloc[14])
        review_status = clean(row.iloc[15])
        note = clean(row.iloc[16])
        primary_evidence = clean(row.iloc[17])
        evidence_grade = clean(row.iloc[18])
        v12_note = clean(row.iloc[19])
        cov = coverage_by_no[no]
        app_key_ids = ids_from_cell(clean(cov.iloc[6]), "AK")
        comprehensive_ids = ids_from_cell(clean(cov.iloc[7]), "CP")
        must_not_miss = is_must_not_miss(no, priority, gate, red_flag_nos)
        diagnosis = {
            "code": code,
            "nameKo": name_ko,
            "nameEn": name_en,
            "category": diagnosis_category(original_category, no),
            "urgency": priority_to_urgency(priority),
            "mustNotMiss": must_not_miss,
            "description": compact(" ".join(first_sentences(suspicion, note, limit=2))),
            "keyDifferentiators": split_cell(suspicion)[:4] + split_cell(mimics)[:3] + split_cell(app_keys)[:4],
            "confirmatoryTests": split_cell(initial_tests)[:4] + split_cell(rule_in)[:4],
            "ruleOutConsiderations": split_cell(rule_out)[:5],
            "redFlags": [item for item in [gate, pitfalls] if item] + (["v1.2 red flag gate"] if no in red_flag_nos else []),
            "originalCategory": original_category,
            "priorityLabel": priority,
            "mustNotMissGate": gate,
            "sourceUrls": source_urls(urls),
            "evidenceLevel": evidence_level,
            "evidenceGrade": evidence_grade,
            "reviewStatus": review_status,
            "primaryEvidence": primary_evidence,
            "v12ChangeNote": v12_note,
            "sourceNote": compact(" | ".join(part for part in [primary_evidence, evidence_grade, v12_note] if part)),
            "checklistIds": {
                "appKey": app_key_ids,
                "comprehensive": comprehensive_ids,
            },
        }
        diagnoses.append(diagnosis)
        name_to_code[name_ko] = code
        code_to_name[code] = name_ko
        code_to_en[code] = name_en

    dangerous_codes = [CODE_BY_NO[int(row.iloc[0])] for _, row in red_flags.iterrows()]

    app_key_rules: list[dict[str, Any]] = []
    app_key_items: list[dict[str, Any]] = []
    for _, row in app_key.iterrows():
        item_id = clean(row.iloc[0])
        section = clean(row.iloc[1])
        label = clean(row.iloc[2])
        status = clean(row.iloc[3])
        related_names = split_cell(clean(row.iloc[6]))
        related_codes = [name_to_code[name] for name in related_names if name in name_to_code]
        red = clean(row.iloc[7]) == "예"
        weights = {code: 1 for code in related_codes}
        app_key_items.append(
            {
                "id": item_id,
                "section": section,
                "labelKo": label,
                "defaultState": status_to_state(status),
                "memo": clean(row.iloc[4]),
                "relatedDiagnosisNames": related_names,
                "relatedDiagnosisCodes": related_codes,
                "redFlag": red,
                "sourceExample": clean(row.iloc[8]),
            }
        )
        app_key_rules.append(
            {
                "id": item_id,
                "labelKo": label,
                "category": checklist_category(section, label, ""),
                "weights": weights,
                **({"redFlagFor": related_codes} if red and related_codes else {}),
                "sourceNote": compact(
                    f"v1.2 AppKey checklist. section={section}; related={'; '.join(related_names)}; source={clean(row.iloc[8])}"
                ),
            }
        )

    comprehensive_items: list[dict[str, Any]] = []
    for _, row in comprehensive.iterrows():
        related_names = split_cell(clean(row.iloc[6]))
        comprehensive_items.append(
            {
                "id": clean(row.iloc[0]),
                "section": clean(row.iloc[1]),
                "labelKo": clean(row.iloc[2]),
                "defaultState": status_to_state(clean(row.iloc[3])),
                "memo": clean(row.iloc[4]),
                "relatedDiagnosisNames": related_names,
                "relatedDiagnosisCodes": [name_to_code[name] for name in related_names if name in name_to_code],
                "redFlag": clean(row.iloc[7]) == "예",
                "impact": clean(row.iloc[8]),
                "sourceColumn": clean(row.iloc[9]),
                "representativeSourceText": clean(row.iloc[10]),
            }
        )

    red_flag_gates: list[dict[str, Any]] = []
    for _, row in red_flags.iterrows():
        no = int(row.iloc[0])
        red_flag_gates.append(
            {
                "no": no,
                "code": CODE_BY_NO[no],
                "nameKo": clean(row.iloc[1]),
                "nameEn": clean(row.iloc[2]),
                "gate": clean(row.iloc[5]),
                "appKeyChecklistIds": ids_from_cell(clean(row.iloc[7]), "AK"),
                "comprehensiveChecklistIds": ids_from_cell(clean(row.iloc[8]), "CP"),
                "caution": clean(row.iloc[13]),
            }
        )

    score_item_records: list[dict[str, Any]] = []
    for _, row in score_items.iterrows():
        related_names = split_cell(clean(row.iloc[2]))
        score_item_records.append(
            {
                "id": clean(row.iloc[0]),
                "labelKo": clean(row.iloc[1]),
                "relatedDiagnosisNames": related_names,
                "relatedDiagnosisCodes": [name_to_code[name] for name in related_names if name in name_to_code],
                "sourceColumn": clean(row.iloc[3]),
                "representativeSourceText": clean(row.iloc[4]),
                "defaultState": status_to_state(clean(row.iloc[5])),
                "memo": clean(row.iloc[6]),
            }
        )

    verbatim_mappings: list[dict[str, Any]] = []
    for _, row in verbatim.iterrows():
        no = int(row.iloc[1])
        verbatim_mappings.append(
            {
                "checklistId": clean(row.iloc[0]),
                "diagnosisNo": no,
                "diagnosisCode": CODE_BY_NO[no],
                "diagnosisNameKo": clean(row.iloc[2]),
                "section": clean(row.iloc[7]),
                "labelKo": clean(row.iloc[8]),
                "impact": clean(row.iloc[9]),
                "sourceColumn": clean(row.iloc[10]),
                "verbatimCell": clean(row.iloc[11]),
                "sourceUrls": source_urls(clean(row.iloc[12])),
                "evidenceLevel": clean(row.iloc[13]),
                "evidenceGrade": clean(row.iloc[14]),
                "v12ChangeNote": clean(row.iloc[15]),
            }
        )

    validation_states = [
        {"labelKo": clean(row.iloc[0]), "state": status_to_state(clean(row.iloc[0]))}
        for _, row in validation.iterrows()
        if clean(row.iloc[0])
    ]

    write(
        ROOT / "src" / "data" / "diagnoses.ts",
        HEADER
        + 'import type { Diagnosis, DiagnosisCode } from "@/types/clinical";\n\n'
        + "export const diagnosisCodeByV12No = "
        + to_ts({str(key): value for key, value in CODE_BY_NO.items()})
        + " as const;\n\n"
        + "export const dangerousBaselineCodes: DiagnosisCode[] = "
        + to_ts(dangerous_codes)
        + ";\n\n"
        + "export const diagnoses: Diagnosis[] = "
        + to_ts(diagnoses)
        + ";\n",
    )

    write(
        ROOT / "src" / "data" / "generatedChecklistRules.ts",
        HEADER
        + 'import type { FindingRule } from "@/types/clinical";\n\n'
        + "export const appKeyFindingRules: FindingRule[] = "
        + to_ts(app_key_rules)
        + ";\n",
    )

    write(
        ROOT / "src" / "data" / "clinicalChecklistData.ts",
        HEADER
        + 'import type { AppKeyChecklistItem, ComprehensiveChecklistItem, RedFlagGate, ScoreItem, VerbatimChecklistMapping, ChecklistEvaluationStateMapping } from "@/types/clinical";\n\n'
        + "export const appKeyChecklistItems = "
        + to_ts(app_key_items)
        + " as unknown as AppKeyChecklistItem[];\n\n"
        + "export const comprehensiveChecklistItems = "
        + to_ts(comprehensive_items)
        + " as unknown as ComprehensiveChecklistItem[];\n\n"
        + "export const redFlagGates = "
        + to_ts(red_flag_gates)
        + " as unknown as RedFlagGate[];\n\n"
        + "export const scoreItems = "
        + to_ts(score_item_records)
        + " as unknown as ScoreItem[];\n\n"
        + "export const verbatimChecklistMappings = "
        + to_ts(verbatim_mappings)
        + " as unknown as VerbatimChecklistMapping[];\n\n"
        + "export const checklistEvaluationStateMappings = "
        + to_ts(validation_states)
        + " as unknown as ChecklistEvaluationStateMapping[];\n",
    )

    write(
        ROOT / "src" / "data" / "sourceReferences.ts",
        HEADER
        + 'import type { ClinicalSourceReference } from "@/types/clinical";\n\n'
        + "export const clinicalSourceReferences: ClinicalSourceReference[] = "
        + to_ts(
            [
                {
                    "key": clean(row.iloc[0]),
                    "title": clean(row.iloc[1]),
                    "url": clean(row.iloc[2]),
                    "coverage": clean(row.iloc[3]),
                    "doiOrFormalUrl": clean(row.iloc[4]),
                    "year": clean(row.iloc[5]),
                    "evidenceType": clean(row.iloc[6]),
                }
                for _, row in sources.iterrows()
                if not row.isna().all()
            ]
        )
        + ";\n",
    )

    disposition_records = [
        {str(col): clean(row[col]) for col in disposition.columns if clean(row[col])}
        for _, row in disposition.iterrows()
        if not row.isna().all()
    ]
    write(
        ROOT / "src" / "data" / "clinicalWorkflow.ts",
        HEADER
        + 'import type { ClinicalWorkflowRule, ClinicalDispositionRow } from "@/types/clinical";\n\n'
        + "export const clinicalWorkflowRules: ClinicalWorkflowRule[] = "
        + to_ts(
            [
                {
                    "id": clean(row.iloc[0]),
                    "ruleKo": clean(row.iloc[1]),
                    "caution": clean(row.iloc[2]),
                }
                for _, row in impl_rules.iterrows()
                if not row.isna().all()
            ]
        )
        + ";\n\n"
        + "export const clinicalDispositionRows: ClinicalDispositionRow[] = "
        + to_ts(disposition_records)
        + ";\n",
    )

    clinical_path = ROOT / "src" / "types" / "clinical.ts"
    clinical = clinical_path.read_text(encoding="utf-8")
    code_union = "export type DiagnosisCode =\n" + "\n".join(
        f'  | "{code}"' for code in CODE_BY_NO.values()
    ) + ";"
    clinical = re.sub(
        r"export type DiagnosisCode =\n(?:  \| \"[A-Z0-9_]+\"\n?)+;",
        code_union,
        clinical,
        count=1,
    )
    diagnosis_type = """export type Diagnosis = {
  code: DiagnosisCode;
  nameKo: string;
  nameEn?: string;
  category: DiagnosisCategory;
  urgency: Urgency;
  mustNotMiss: boolean;
  description: string;
  keyDifferentiators: string[];
  confirmatoryTests: string[];
  ruleOutConsiderations: string[];
  redFlags: string[];
  originalCategory?: string;
  priorityLabel?: string;
  mustNotMissGate?: string;
  sourceUrls?: string[];
  evidenceLevel?: string;
  evidenceGrade?: string;
  reviewStatus?: string;
  primaryEvidence?: string;
  v12ChangeNote?: string;
  sourceNote?: string;
  checklistIds?: {
    appKey: string[];
    comprehensive: string[];
  };
};"""
    clinical = re.sub(r"export type Diagnosis = \{.*?\n\};", diagnosis_type, clinical, count=1, flags=re.S)
    extra_types = """
export type AppKeyChecklistItem = {
  id: string;
  section: string;
  labelKo: string;
  defaultState: FindingState;
  memo: string;
  relatedDiagnosisNames: string[];
  relatedDiagnosisCodes: DiagnosisCode[];
  redFlag: boolean;
  sourceExample: string;
};

export type ComprehensiveChecklistItem = {
  id: string;
  section: string;
  labelKo: string;
  defaultState: FindingState;
  memo: string;
  relatedDiagnosisNames: string[];
  relatedDiagnosisCodes: DiagnosisCode[];
  redFlag: boolean;
  impact: string;
  sourceColumn: string;
  representativeSourceText: string;
};

export type RedFlagGate = {
  no: number;
  code: DiagnosisCode;
  nameKo: string;
  nameEn: string;
  gate: string;
  appKeyChecklistIds: string[];
  comprehensiveChecklistIds: string[];
  caution: string;
};

export type ScoreItem = {
  id: string;
  labelKo: string;
  relatedDiagnosisNames: string[];
  relatedDiagnosisCodes: DiagnosisCode[];
  sourceColumn: string;
  representativeSourceText: string;
  defaultState: FindingState;
  memo: string;
};

export type VerbatimChecklistMapping = {
  checklistId: string;
  diagnosisNo: number;
  diagnosisCode: DiagnosisCode;
  diagnosisNameKo: string;
  section: string;
  labelKo: string;
  impact: string;
  sourceColumn: string;
  verbatimCell: string;
  sourceUrls: string[];
  evidenceLevel: string;
  evidenceGrade: string;
  v12ChangeNote: string;
};

export type ChecklistEvaluationStateMapping = {
  labelKo: string;
  state: FindingState;
};

export type ClinicalSourceReference = {
  key: string;
  title: string;
  url: string;
  coverage: string;
  doiOrFormalUrl: string;
  year: string;
  evidenceType: string;
};

export type ClinicalWorkflowRule = {
  id: string;
  ruleKo: string;
  caution: string;
};

export type ClinicalDispositionRow = Record<string, string>;
"""
    if "export type AppKeyChecklistItem" not in clinical:
        clinical = clinical.replace("export type FindingCategory =", extra_types + "\nexport type FindingCategory =", 1)
    write(clinical_path, clinical)

    summary = {
        "diagnoses": len(diagnoses),
        "appKeyChecklist": len(app_key_items),
        "comprehensiveChecklist": len(comprehensive_items),
        "redFlagGates": len(red_flag_gates),
        "scoreItems": len(score_item_records),
        "verbatimMappings": len(verbatim_mappings),
        "sourceReferences": len(rows_to_records(sources)),
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
