// Generated by scripts/importClinicalXlsx.py from chest pain v1.2 workbooks.
// Do not edit generated arrays by hand; update the source workbook or generator instead.
import type { ClinicalWorkflowRule, ClinicalDispositionRow } from "@/types/clinical";

export const clinicalWorkflowRules: ClinicalWorkflowRule[] = [
  {
    "id": "R01",
    "ruleKo": "질환 상태값을 4단계로 둔다",
    "caution": "not evaluated / active concern / low probability / clinically ruled out. 고위험 질환은 clinically ruled out 전까지 숨기지 않음."
  },
  {
    "id": "R02",
    "ruleKo": "red flag override",
    "caution": "저혈압, 저산소, 실신, 신경결손, 새 murmur, 지속 severe pain, immunocompromise, 임신/산후, 항응고, 고에너지 외상은 관련 게이트를 강제 표시."
  },
  {
    "id": "R03",
    "ruleKo": "ACS single-test 금지",
    "caution": "초기 ECG와 단일 troponin이 정상이어도 symptom onset이 짧거나 고위험이면 serial pathway 유지."
  },
  {
    "id": "R04",
    "ruleKo": "D-dimer 사용 제한",
    "caution": "PE/AAS 모두 high pretest probability에서는 음성 D-dimer로 종료하지 않음. 나이보정/임신/암/입원 상태는 별도 규칙."
  },
  {
    "id": "R05",
    "ruleKo": "압통으로 ACS 배제 금지",
    "caution": "흉벽 압통은 MSK 가능성을 올리지만 ACS/PE를 자동 배제하지 않음."
  },
  {
    "id": "R06",
    "ruleKo": "psych/functional 마지막",
    "caution": "공황/불안/기능성 흉통은 적절한 심폐·식도·외과 red flag 평가 후에만 상위 확정 후보로 표시."
  },
  {
    "id": "R07",
    "ruleKo": "영상 음성의 시간축",
    "caution": "초기 CXR는 small PTX, early pneumonia, early pulmonary contusion, esophageal rupture를 놓칠 수 있어 의심 지속 시 CT/US/반복검사 권고."
  },
  {
    "id": "R08",
    "ruleKo": "임신/산후 별도 위험",
    "caution": "PE, SCAD, aortic dissection, peripartum cardiomyopathy, GERD/담도질환 확률을 별도 조정."
  },
  {
    "id": "R09",
    "ruleKo": "검사결과-진단명 분리",
    "caution": "troponin elevation은 ACS가 아니라 myocardial injury 신호. type 1 MI, type 2 MI, myocarditis, PE, Takotsubo를 병렬 평가."
  },
  {
    "id": "R10",
    "ruleKo": "치료 전 금기 확인",
    "caution": "대동맥박리/식도파열/출혈성 질환 가능성이 남아 있으면 항응고·혈전용해·항혈소판 결정에 경고 표시."
  },
  {
    "id": "R11",
    "ruleKo": "hs-cTn-점수 매칭 강제",
    "caution": "0/1h·0/2h 알고리즘은 기관의 assay-specific 컷오프를 사용. HEART/EDACS는 conventional troponin 기반 검증 점수이므로 hs-cTn CDP와 혼용 금지. hs-cTn를 99백분위 미만으로 보고하지 않는 기관은 위험점수 필수."
  },
  {
    "id": "R12",
    "ruleKo": "근거등급 표기 의무",
    "caution": "각 rule-in/rule-out/pitfall 주장에 인용 가이드라인의 COR/LOE를 셀 단위로 부착. 미검증 항목은 '원문 대조 필요'로 표시하고 임의 등급 부여 금지."
  },
  {
    "id": "R13",
    "ruleKo": "처분(disposition) 연동",
    "caution": "STEMI 배제 후 ACS 의심 환자는 04_Disposition의 저/중/고위험 경로로 분기. 비-ACS 치명진단은 각 노드 영상기준을 따름."
  }
];

export const clinicalDispositionRows: ClinicalDispositionRow[] = [
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "근거: 2021 AHA/ACC/Multisociety Chest Pain Guideline (Figure 8) · 2022 ACC ECDP · 2023 ESC ACS"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "전제: ① 즉각적 생명위협 게이트(STEMI·AAS·PE·tension PTX·tamponade·식도파열·천공·shock)를 먼저 통과시킬 것(01·R02). ② STEMI 또는 STEMI-equivalent면 troponin 대기 없이 재관류 경로."
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "위험군",
    "Unnamed: 1": "정의 (30일 사망/MACE)",
    "Unnamed: 2": "진입 기준 (hs-cTn · ECG · CDP)",
    "Unnamed: 3": "권고 처분",
    "Unnamed: 4": "추가 심장검사",
    "Unnamed: 5": "근거등급(검증)",
    "Unnamed: 6": "출처 Key"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "저위험",
    "Unnamed: 1": "<1%",
    "Unnamed: 2": "hs-cTn CDP로 rule-out + 초기 ECG 비허혈성 (hs-cTn를 99백분위 미만으로 보고하는 기관). conventional cTn 기관: modified HEART ≤3 또는 EDACS <16.",
    "Unnamed: 3": "추가 긴급 심장검사 없이 귀가 + 밀착 외래 추적. hs-cTn CDP로 rule-out 시 위험점수 적용 불필요.",
    "Unnamed: 4": "일상적으로 불필요 (Testing Not Needed Routinely).",
    "Unnamed: 5": "저위험 외래검사 보류 = COR IIa; hs-cTn 0/1h·0/2h 알고리즘 = 강한 근거(ESC Class I)",
    "Unnamed: 6": "ChestPain2021 · ChestPainECDP2022 · ESC_ACS2023"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "중간위험",
    "Unnamed: 1": "1–10% (대략)",
    "Unnamed: 2": "저위험·고위험 어디에도 명확히 속하지 않음. 비결정적 검사, 중간 CDP 점수, 위험인자 다수, 전형 증상이나 초기 음성.",
    "Unnamed: 3": "관찰 후 결정. 조기 퇴원 대상 아님. 구조검사로 분기.",
    "Unnamed: 4": "기능검사(stress) 또는 CCTA. known obstructive CAD → 기능검사; nonobstructive/미확인 → CCTA. 중간위험이 영상검사 이득 최대.",
    "Unnamed: 5": "중간위험 영상/검사 = 이득 집단(가이드라인 권고)",
    "Unnamed: 6": "ChestPain2021 · ESC_ACS2023"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "고위험",
    "Unnamed: 1": ">10% / 객관적 허혈·손상",
    "Unnamed: 2": "다음 중 1개 이상: 새 허혈성 ECG 변화 / cTn-확인 심근손상 / 새 좌심실 수축기능부전 / 기능검사상 새 중등도-중증 허혈 / 혈역학 불안정 / 고위험 CDP 점수.",
    "Unnamed: 3": "입원 + 순환기. 침습적 관상동맥조영(ICA) 경로. ACS 확정 시 항혈전·재관류는 ACS2025(치료) 따름.",
    "Unnamed: 4": "침습적 관상동맥조영(ICA).",
    "Unnamed: 5": "ICA 권고(true ACS·불안정·고위험 평가)",
    "Unnamed: 6": "ChestPain2021 · ESC_ACS2023 · ACS2025(치료)"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "주의·운영 규칙"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "N1 — hs-cTn serial",
    "Unnamed: 1": "ED 도착 후 1·2·3시간 재검. delta(상승/하강 변화) + 절대값을 assay-specific 컷오프로 해석. 단일 음성 결과로 조기 MI 배제 금지(R03). symptom onset이 짧으면 serial 경로 유지."
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "N2 — 위험점수 적용 규칙",
    "Unnamed: 1": "HEART·EDACS는 conventional cTn 기반으로 개발/검증된 점수. hs-cTn를 99백분위 미만으로 보고하는 기관은 CDP rule-out 후 위험점수 불필요. conventional cTn(또는 99백분위 미만 미보고) 기관은 단독 NPV 부족으로 위험점수 필수."
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "N3 — modified HEART(HEAR)/EDACS",
    "Unnamed: 1": "cTn으로 MI가 배제된 뒤의 임상 위험 층화용. troponin 항목을 뺀 변형 점수."
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "N4 — 비-ACS 치명진단 처분",
    "Unnamed: 1": "아래 표는 ACS 경로. PE·AAS·tension PTX·tamponade·식도파열·천공은 각 노드의 영상기준으로 별도 처분(다음 표)."
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "비-ACS 치명진단 처분 (각 노드 영상기준 연동)"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "치명진단",
    "Unnamed: 1": "위험층화/도구",
    "Unnamed: 2": "확진 영상",
    "Unnamed: 3": "핵심 처분 원칙",
    "Unnamed: 4": "출처 Key"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "폐색전증 (PE)",
    "Unnamed: 1": "Wells/Geneva + PERC(저확률) / D-dimer(저·중확률, 연령보정)",
    "Unnamed: 2": "CTPA (대안 V/Q)",
    "Unnamed: 3": "고확률은 음성 D-dimer로 배제 금지; 혈역학 불안정=고위험 재관류",
    "Unnamed: 4": "PE2019"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "급성 대동맥증후군",
    "Unnamed: 1": "ADD-RS (+저확률 D-dimer)",
    "Unnamed: 2": "CTA chest/abdo/pelvis (불안정 TEE)",
    "Unnamed: 3": "중등도 이상은 영상 필수; 항응고·혈전용해 전 반드시 고려",
    "Unnamed: 4": "Aortic2022"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "긴장성 기흉",
    "Unnamed: 1": "임상진단(혈역학)",
    "Unnamed: 2": "치료 후 CXR/US/CT",
    "Unnamed: 3": "영상 대기 말고 즉시 needle/finger 감압 후 chest tube",
    "Unnamed: 4": "BTSPleural2023 · MSDTensionPTX"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "심장압전",
    "Unnamed: 1": "POCUS/echo physiology",
    "Unnamed: 2": "Echo(RA/RV collapse, IVC plethora)",
    "Unnamed: 3": "불안정 시 pericardiocentesis/외과 배액",
    "Unnamed: 4": "MyoPeri2025"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "식도파열 (Boerhaave)",
    "Unnamed: 1": "구토 후 흉통 자동 게이트",
    "Unnamed: 2": "CT chest + 물용해성 조영 / CT esophagography",
    "Unnamed: 3": "NPO·광범위 항생제·외과/GI; Mallory-Weiss와 혼동 금지",
    "Unnamed: 4": "WSES_Esoph2019"
  },
  {
    "흉통 위험층화·처분 경로 (STEMI 배제 후 ACS 의심)": "천공성 소화성 궤양",
    "Unnamed: 1": "복막염/free air",
    "Unnamed: 2": "Upright CXR / CT abdo·pelvis",
    "Unnamed: 3": "외과 응급·항생제; 진통으로 압통 감소해도 배제 아님",
    "Unnamed: 4": "WSES_PUD2019"
  }
];
