// Generated by scripts/importClinicalXlsx.py from chest pain v1.2 workbooks.
// Do not edit generated arrays by hand; update the source workbook or generator instead.
import type { FindingRule } from "@/types/clinical";

export const appKeyFindingRules: FindingRule[] = [
  {
    "id": "AK-001",
    "labelKo": "shock",
    "category": "vital",
    "weights": {
      "TPTX": 1
    },
    "redFlagFor": [
      "TPTX"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=활력/즉시위험; related=긴장성 기흉; source=#20 긴장성 기흉 / 앱 체크리스트 키: unilateral breath sound; shock; immediate decompression"
  },
  {
    "id": "AK-002",
    "labelKo": "hypertension/tachy",
    "category": "vital",
    "weights": {
      "STIMULANT_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=활력/즉시위험; related=자극제 관련 관상동맥 허혈/연축; source=#61 자극제 관련 관상동맥 허혈/연축 / 앱 체크리스트 키: stimulant use; hypertension/tachy; ECG/troponin"
  },
  {
    "id": "AK-003",
    "labelKo": "severe BP",
    "category": "vital",
    "weights": {
      "HTN_EMERG": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=활력/즉시위험; related=고혈압 응급증 관련 흉통; source=#18 고혈압 응급증 관련 흉통 / 앱 체크리스트 키: severe BP; organ damage; ECG/troponin/renal/neuro"
  },
  {
    "id": "AK-004",
    "labelKo": "tachypnea",
    "category": "vital",
    "weights": {
      "HVS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=활력/즉시위험; related=과호흡증후군; source=#55 과호흡증후군 / 앱 체크리스트 키: tachypnea; paresthesia; VBG; after rule-out"
  },
  {
    "id": "AK-005",
    "labelKo": "dyspnea",
    "category": "history",
    "weights": {
      "AHF": 1,
      "PE": 1
    },
    "redFlagFor": [
      "AHF",
      "PE"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=급성 심부전 / 폐부종; 폐색전증; source=#12 급성 심부전 / 폐부종 / 앱 체크리스트 키: dyspnea; crackles; BNP; CXR/POCUS --- #19 폐색전증 / 앱 체크리스트 키: pleuritic pain; dyspnea; DVT; Wells/PERC/D-dimer; CTPA"
  },
  {
    "id": "AK-006",
    "labelKo": "pleuritic pain",
    "category": "history",
    "weights": {
      "PE": 1,
      "PLEUR": 1
    },
    "redFlagFor": [
      "PE",
      "PLEUR"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=폐색전증; 흉막염; source=#19 폐색전증 / 앱 체크리스트 키: pleuritic pain; dyspnea; DVT; Wells/PERC/D-dimer; CTPA --- #24 흉막염 / 앱 체크리스트 키: pleuritic pain; rub; CXR/PE screen"
  },
  {
    "id": "AK-007",
    "labelKo": "pleuritic/positional",
    "category": "history",
    "weights": {
      "PERI": 1,
      "AUTOIMMUNE_SEROSITIS": 1
    },
    "redFlagFor": [
      "PERI",
      "AUTOIMMUNE_SEROSITIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=심낭염 / 심낭삼출 / 심장압전; 자가면역성 장막염; source=#10 심낭염 / 심낭삼출 / 심장압전 / 앱 체크리스트 키: pleuritic/positional; rub; diffuse ST/PR; echo --- #85 자가면역성 장막염 / 앱 체크리스트 키: SLE/RA; pleuritic/positional; effusion; labs"
  },
  {
    "id": "AK-008",
    "labelKo": "abrupt back pain",
    "category": "history",
    "weights": {
      "AAS_IMH_PAU": 1
    },
    "redFlagFor": [
      "AAS_IMH_PAU"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=급성 대동맥 증후군: 벽내혈종/관통성 궤양; source=#59 급성 대동맥 증후군: 벽내혈종/관통성 궤양 / 앱 체크리스트 키: abrupt back pain; aortic risk; CTA protocol"
  },
  {
    "id": "AK-009",
    "labelKo": "diaphoresis",
    "category": "history",
    "weights": {
      "STEMI": 1
    },
    "redFlagFor": [
      "STEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=ST분절상승 심근경색; source=#1 ST분절상승 심근경색 / 앱 체크리스트 키: ECG; serial troponin; ACS risk; radiation; diaphoresis"
  },
  {
    "id": "AK-010",
    "labelKo": "fever/chest pain",
    "category": "history",
    "weights": {
      "SICKLE_ACUTE_CHEST": 1
    },
    "redFlagFor": [
      "SICKLE_ACUTE_CHEST"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=겸상적혈구 급성흉부증후군; source=#69 겸상적혈구 급성흉부증후군 / 앱 체크리스트 키: SCD; fever/chest pain; new infiltrate; hypoxia"
  },
  {
    "id": "AK-011",
    "labelKo": "radiation",
    "category": "history",
    "weights": {
      "STEMI": 1
    },
    "redFlagFor": [
      "STEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=ST분절상승 심근경색; source=#1 ST분절상승 심근경색 / 앱 체크리스트 키: ECG; serial troponin; ACS risk; radiation; diaphoresis"
  },
  {
    "id": "AK-012",
    "labelKo": "sudden back/chest pain",
    "category": "history",
    "weights": {
      "TAA": 1
    },
    "redFlagFor": [
      "TAA"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=흉부 대동맥류 파열 또는 누출; source=#9 흉부 대동맥류 파열 또는 누출 / 앱 체크리스트 키: known aneurysm; sudden back/chest pain; CTA"
  },
  {
    "id": "AK-013",
    "labelKo": "fever",
    "category": "history",
    "weights": {
      "CHOLE": 1,
      "SUBPHRENIC_ABSCESS": 1,
      "SC_JOINT_INFECTION": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=급성 담낭염; 횡격막하 농양 / 간농양; 흉쇄관절 감염 / 골수염; source=#39 급성 담낭염 / 앱 체크리스트 키: RUQ pain; Murphy; fever; US; Tokyo criteria --- #79 횡격막하 농양 / 간농양 / 앱 체크리스트 키: fever; RUQ/shoulder; post-op; CT/US --- #82 흉쇄관절 감염 / 골수염 / 앱 체크리스트 키: SC joint swelling; fever; IVDU/diabetes; CT/MRI/culture"
  },
  {
    "id": "AK-014",
    "labelKo": "syncope",
    "category": "history",
    "weights": {
      "HCM": 1,
      "ARR": 1,
      "ANOMALOUS_CORONARY": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=비후성 심근병증; 부정맥 관련 흉통; 선천성 관상동맥 이상 / 심근교; source=#15 비후성 심근병증 / 앱 체크리스트 키: young exertional; syncope; family sudden death; echo/CMR --- #16 부정맥 관련 흉통 / 앱 체크리스트 키: palpitation; syncope; ECG monitor; electrolytes --- #65 선천성 관상동맥 이상 / 심근교 / 앱 체크리스트 키: young exertional; syncope; CCTA coronary anatomy"
  },
  {
    "id": "AK-015",
    "labelKo": "hemoptysis",
    "category": "history",
    "weights": {
      "PULM_INFARCT": 1,
      "LUNGCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=폐경색; 폐암 / 흉막종양; source=#26 폐경색 / 앱 체크리스트 키: PE symptoms; hemoptysis; wedge opacity; CTPA --- #30 폐암 / 흉막종양 / 앱 체크리스트 키: smoking; weight loss; hemoptysis; CT/biopsy"
  },
  {
    "id": "AK-016",
    "labelKo": "weight loss",
    "category": "history",
    "weights": {
      "LUNGCA": 1,
      "ESOPHAGEAL_CANCER": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=폐암 / 흉막종양; 식도암; source=#30 폐암 / 흉막종양 / 앱 체크리스트 키: smoking; weight loss; hemoptysis; CT/biopsy --- #76 식도암 / 앱 체크리스트 키: progressive dysphagia; weight loss; EGD biopsy"
  },
  {
    "id": "AK-017",
    "labelKo": "chronic widespread pain",
    "category": "history",
    "weights": {
      "FIBRO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=섬유근통; source=#51 섬유근통 / 앱 체크리스트 키: chronic widespread pain; fatigue; sleep"
  },
  {
    "id": "AK-018",
    "labelKo": "exertional chest pain/syncope",
    "category": "history",
    "weights": {
      "AS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=대동맥판 협착; source=#13 대동맥판 협착 / 앱 체크리스트 키: exertional chest pain/syncope; systolic murmur; TTE"
  },
  {
    "id": "AK-019",
    "labelKo": "exertional syncope",
    "category": "history",
    "weights": {
      "PH_RV_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=폐고혈압 / 우심실 허혈; source=#64 폐고혈압 / 우심실 허혈 / 앱 체크리스트 키: exertional syncope; RV signs; echo/RHC"
  },
  {
    "id": "AK-020",
    "labelKo": "fever cough sputum",
    "category": "history",
    "weights": {
      "PNA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=폐렴; source=#23 폐렴 / 앱 체크리스트 키: fever cough sputum; crackles; CXR"
  },
  {
    "id": "AK-021",
    "labelKo": "fever pneumonia",
    "category": "history",
    "weights": {
      "EMP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=농흉 / 흉막감염; source=#66 농흉 / 흉막감염 / 앱 체크리스트 키: fever pneumonia; effusion; pleural pH/glucose; US"
  },
  {
    "id": "AK-022",
    "labelKo": "foul sputum",
    "category": "history",
    "weights": {
      "LUNG_ABSCESS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=폐농양; source=#71 폐농양 / 앱 체크리스트 키: subacute fever; foul sputum; CT cavity"
  },
  {
    "id": "AK-023",
    "labelKo": "palpitation",
    "category": "history",
    "weights": {
      "ARR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=부정맥 관련 흉통; source=#16 부정맥 관련 흉통 / 앱 체크리스트 키: palpitation; syncope; ECG monitor; electrolytes"
  },
  {
    "id": "AK-024",
    "labelKo": "palpitations",
    "category": "history",
    "weights": {
      "MVP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=승모판 탈출증; source=#14 승모판 탈출증 / 앱 체크리스트 키: click/murmur; palpitations; TTE"
  },
  {
    "id": "AK-025",
    "labelKo": "paresthesia",
    "category": "history",
    "weights": {
      "HVS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=과호흡증후군; source=#55 과호흡증후군 / 앱 체크리스트 키: tachypnea; paresthesia; VBG; after rule-out"
  },
  {
    "id": "AK-026",
    "labelKo": "pleuritic",
    "category": "history",
    "weights": {
      "VIRAL_PLEURITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=바이러스성 흉막염 / 유행성 흉통; source=#67 바이러스성 흉막염 / 유행성 흉통 / 앱 체크리스트 키: URI prodrome; pleuritic; normal CXR after red flags"
  },
  {
    "id": "AK-027",
    "labelKo": "postprandial severe pain",
    "category": "history",
    "weights": {
      "STRANGULATED_HERNIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=감돈/교액성 식도열공·횡격막 탈장; source=#90 감돈/교액성 식도열공·횡격막 탈장 / 앱 체크리스트 키: postprandial severe pain; vomiting; hernia history; CT"
  },
  {
    "id": "AK-028",
    "labelKo": "rest/night pain",
    "category": "history",
    "weights": {
      "VSA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=관상동맥 연축 / 변이형 협심증; source=#5 관상동맥 연축 / 변이형 협심증 / 앱 체크리스트 키: rest/night pain; transient ST; nitrate response; stimulant"
  },
  {
    "id": "AK-029",
    "labelKo": "sputum",
    "category": "history",
    "weights": {
      "COPD_EXAC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=COPD 급성 악화; source=#29 COPD 급성 악화 / 앱 체크리스트 키: COPD history; sputum; ABG; CXR"
  },
  {
    "id": "AK-030",
    "labelKo": "subacute fever",
    "category": "history",
    "weights": {
      "LUNG_ABSCESS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=폐농양; source=#71 폐농양 / 앱 체크리스트 키: subacute fever; foul sputum; CT cavity"
  },
  {
    "id": "AK-031",
    "labelKo": "weight loss/night sweat",
    "category": "history",
    "weights": {
      "TB_PLEURITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=문진/증상; related=결핵성 흉막염 / 폐결핵; source=#68 결핵성 흉막염 / 폐결핵 / 앱 체크리스트 키: weight loss/night sweat; TB exposure; effusion; AFB/ADA"
  },
  {
    "id": "AK-032",
    "labelKo": "trauma",
    "category": "history",
    "weights": {
      "TRAUMATIC_PTX_HEMOTHORAX": 1,
      "CHEST_CONTUSION": 1
    },
    "redFlagFor": [
      "TRAUMATIC_PTX_HEMOTHORAX",
      "CHEST_CONTUSION"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=외상성 기흉 / 혈흉; 흉벽 타박상 / 외상 후 흉통; source=#22 외상성 기흉 / 혈흉 / 앱 체크리스트 키: trauma; breath sound; eFAST/CXR/CT --- #47 흉벽 타박상 / 외상 후 흉통 / 앱 체크리스트 키: trauma; ecchymosis; eFAST/CXR/CT"
  },
  {
    "id": "AK-033",
    "labelKo": "ACS risk",
    "category": "history",
    "weights": {
      "STEMI": 1
    },
    "redFlagFor": [
      "STEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=ST분절상승 심근경색; source=#1 ST분절상승 심근경색 / 앱 체크리스트 키: ECG; serial troponin; ACS risk; radiation; diaphoresis"
  },
  {
    "id": "AK-034",
    "labelKo": "DVT",
    "category": "history",
    "weights": {
      "PE": 1
    },
    "redFlagFor": [
      "PE"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=폐색전증; source=#19 폐색전증 / 앱 체크리스트 키: pleuritic pain; dyspnea; DVT; Wells/PERC/D-dimer; CTPA"
  },
  {
    "id": "AK-035",
    "labelKo": "FMD",
    "category": "history",
    "weights": {
      "SCAD": 1
    },
    "redFlagFor": [
      "SCAD"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=자발성 관상동맥 박리; source=#7 자발성 관상동맥 박리 / 앱 체크리스트 키: young female ACS; postpartum; FMD; angiography"
  },
  {
    "id": "AK-036",
    "labelKo": "SCD",
    "category": "history",
    "weights": {
      "SICKLE_ACUTE_CHEST": 1
    },
    "redFlagFor": [
      "SICKLE_ACUTE_CHEST"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=겸상적혈구 급성흉부증후군; source=#69 겸상적혈구 급성흉부증후군 / 앱 체크리스트 키: SCD; fever/chest pain; new infiltrate; hypoxia"
  },
  {
    "id": "AK-037",
    "labelKo": "aortic risk",
    "category": "history",
    "weights": {
      "AAS_IMH_PAU": 1
    },
    "redFlagFor": [
      "AAS_IMH_PAU"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=급성 대동맥 증후군: 벽내혈종/관통성 궤양; source=#59 급성 대동맥 증후군: 벽내혈종/관통성 궤양 / 앱 체크리스트 키: abrupt back pain; aortic risk; CTA protocol"
  },
  {
    "id": "AK-038",
    "labelKo": "high-energy trauma",
    "category": "history",
    "weights": {
      "TRAUMATIC_AORTIC_INJURY": 1
    },
    "redFlagFor": [
      "TRAUMATIC_AORTIC_INJURY"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=외상성 대혈관 손상; source=#88 외상성 대혈관 손상 / 앱 체크리스트 키: high-energy trauma; widened mediastinum; CTA"
  },
  {
    "id": "AK-039",
    "labelKo": "known aneurysm",
    "category": "history",
    "weights": {
      "TAA": 1
    },
    "redFlagFor": [
      "TAA"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=흉부 대동맥류 파열 또는 누출; source=#9 흉부 대동맥류 파열 또는 누출 / 앱 체크리스트 키: known aneurysm; sudden back/chest pain; CTA"
  },
  {
    "id": "AK-040",
    "labelKo": "postpartum",
    "category": "history",
    "weights": {
      "SCAD": 1
    },
    "redFlagFor": [
      "SCAD"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=자발성 관상동맥 박리; source=#7 자발성 관상동맥 박리 / 앱 체크리스트 키: young female ACS; postpartum; FMD; angiography"
  },
  {
    "id": "AK-041",
    "labelKo": "immunocompromise",
    "category": "history",
    "weights": {
      "ESOPH": 1,
      "PILL_INFECTIOUS_EOE_ESOPHAGITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=식도염; 약제성/감염성/호산구성 식도염; source=#32 식도염 / 앱 체크리스트 키: odynophagia; dysphagia; immunocompromise; EGD --- #75 약제성/감염성/호산구성 식도염 / 앱 체크리스트 키: pill history; odynophagia; immunocompromise; EGD biopsy"
  },
  {
    "id": "AK-042",
    "labelKo": "ACS with low CAD risk",
    "category": "history",
    "weights": {
      "CORONARY_EMBOLISM": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=관상동맥 색전/혈전증; source=#60 관상동맥 색전/혈전증 / 앱 체크리스트 키: AF/valve/IE; ACS with low CAD risk; echo/TEE"
  },
  {
    "id": "AK-043",
    "labelKo": "CO exposure",
    "category": "history",
    "weights": {
      "CO_POISONING_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=일산화탄소 중독 관련 심근허혈; source=#86 일산화탄소 중독 관련 심근허혈 / 앱 체크리스트 키: CO exposure; headache; multiple patients; COHb/troponin"
  },
  {
    "id": "AK-044",
    "labelKo": "COPD history",
    "category": "history",
    "weights": {
      "COPD_EXAC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=COPD 급성 악화; source=#29 COPD 급성 악화 / 앱 체크리스트 키: COPD history; sputum; ABG; CXR"
  },
  {
    "id": "AK-045",
    "labelKo": "IVDU/diabetes",
    "category": "history",
    "weights": {
      "SC_JOINT_INFECTION": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=흉쇄관절 감염 / 골수염; source=#82 흉쇄관절 감염 / 골수염 / 앱 체크리스트 키: SC joint swelling; fever; IVDU/diabetes; CT/MRI/culture"
  },
  {
    "id": "AK-046",
    "labelKo": "NSAID",
    "category": "history",
    "weights": {
      "PUD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=소화성 궤양; source=#36 소화성 궤양 / 앱 체크리스트 키: epigastric burning; NSAID; melena; EGD"
  },
  {
    "id": "AK-047",
    "labelKo": "alcohol/gallstone",
    "category": "history",
    "weights": {
      "PANC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=급성 췌장염; source=#41 급성 췌장염 / 앱 체크리스트 키: epigastric to back; lipase; alcohol/gallstone"
  },
  {
    "id": "AK-048",
    "labelKo": "blunt trauma",
    "category": "history",
    "weights": {
      "PULM_CONTUSION_FLAIL": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=폐좌상 / 동요흉; source=#89 폐좌상 / 동요흉 / 앱 체크리스트 키: blunt trauma; hypoxia; CT/CXR; paradoxical movement"
  },
  {
    "id": "AK-049",
    "labelKo": "family sudden death",
    "category": "history",
    "weights": {
      "HCM": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=비후성 심근병증; source=#15 비후성 심근병증 / 앱 체크리스트 키: young exertional; syncope; family sudden death; echo/CMR"
  },
  {
    "id": "AK-050",
    "labelKo": "hernia history",
    "category": "history",
    "weights": {
      "STRANGULATED_HERNIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=감돈/교액성 식도열공·횡격막 탈장; source=#90 감돈/교액성 식도열공·횡격막 탈장 / 앱 체크리스트 키: postprandial severe pain; vomiting; hernia history; CT"
  },
  {
    "id": "AK-051",
    "labelKo": "pill history",
    "category": "history",
    "weights": {
      "PILL_INFECTIOUS_EOE_ESOPHAGITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=약제성/감염성/호산구성 식도염; source=#75 약제성/감염성/호산구성 식도염 / 앱 체크리스트 키: pill history; odynophagia; immunocompromise; EGD biopsy"
  },
  {
    "id": "AK-052",
    "labelKo": "smoking",
    "category": "history",
    "weights": {
      "LUNGCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=폐암 / 흉막종양; source=#30 폐암 / 흉막종양 / 앱 체크리스트 키: smoking; weight loss; hemoptysis; CT/biopsy"
  },
  {
    "id": "AK-053",
    "labelKo": "stimulant",
    "category": "history",
    "weights": {
      "VSA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=관상동맥 연축 / 변이형 협심증; source=#5 관상동맥 연축 / 변이형 협심증 / 앱 체크리스트 키: rest/night pain; transient ST; nitrate response; stimulant"
  },
  {
    "id": "AK-054",
    "labelKo": "tall thin/smoking",
    "category": "history",
    "weights": {
      "PTX": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=자연기흉; source=#21 자연기흉 / 앱 체크리스트 키: sudden unilateral; tall thin/smoking; CXR/US"
  },
  {
    "id": "AK-055",
    "labelKo": "trauma/CPR/cough",
    "category": "history",
    "weights": {
      "RIB": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=늑골골절; source=#46 늑골골절 / 앱 체크리스트 키: trauma/CPR/cough; focal tenderness; CXR/CT"
  },
  {
    "id": "AK-056",
    "labelKo": "trauma/exertion",
    "category": "history",
    "weights": {
      "STRAIN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=흉벽 근육통 / 근육염좌; source=#45 흉벽 근육통 / 근육염좌 / 앱 체크리스트 키: movement-related; reproducible; trauma/exertion"
  },
  {
    "id": "AK-057",
    "labelKo": "zoster/trauma",
    "category": "history",
    "weights": {
      "ICN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위험인자/과거력; related=늑간신경통; source=#48 늑간신경통 / 앱 체크리스트 키: dermatomal; neuropathic; zoster/trauma"
  },
  {
    "id": "AK-058",
    "labelKo": "rub",
    "category": "physical",
    "weights": {
      "PERI": 1,
      "PLEUR": 1
    },
    "redFlagFor": [
      "PERI",
      "PLEUR"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=심낭염 / 심낭삼출 / 심장압전; 흉막염; source=#10 심낭염 / 심낭삼출 / 심장압전 / 앱 체크리스트 키: pleuritic/positional; rub; diffuse ST/PR; echo --- #24 흉막염 / 앱 체크리스트 키: pleuritic pain; rub; CXR/PE screen"
  },
  {
    "id": "AK-059",
    "labelKo": "subcutaneous emphysema",
    "category": "physical",
    "weights": {
      "PMED": 1,
      "BOER": 1
    },
    "redFlagFor": [
      "PMED",
      "BOER"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=종격동기종 / 기종격; 식도파열; source=#27 종격동기종 / 기종격 / 앱 체크리스트 키: subcutaneous emphysema; vomiting/asthma; CT --- #34 식도파열 / 앱 체크리스트 키: vomiting before pain; subcutaneous emphysema; CT esophagram"
  },
  {
    "id": "AK-060",
    "labelKo": "JVD",
    "category": "physical",
    "weights": {
      "TAMPONADE": 1
    },
    "redFlagFor": [
      "TAMPONADE"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=심장압전 독립 게이트; source=#63 심장압전 독립 게이트 / 앱 체크리스트 키: hypotension; JVD; pulsus; POCUS/echo"
  },
  {
    "id": "AK-061",
    "labelKo": "breath sound",
    "category": "physical",
    "weights": {
      "TRAUMATIC_PTX_HEMOTHORAX": 1
    },
    "redFlagFor": [
      "TRAUMATIC_PTX_HEMOTHORAX"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=외상성 기흉 / 혈흉; source=#22 외상성 기흉 / 혈흉 / 앱 체크리스트 키: trauma; breath sound; eFAST/CXR/CT"
  },
  {
    "id": "AK-062",
    "labelKo": "neuro",
    "category": "physical",
    "weights": {
      "DIS": 1
    },
    "redFlagFor": [
      "DIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=급성 대동맥 박리; source=#8 급성 대동맥 박리 / 앱 체크리스트 키: abrupt tearing; pulse deficit; neuro; CTA aorta"
  },
  {
    "id": "AK-063",
    "labelKo": "peritonitis",
    "category": "physical",
    "weights": {
      "PERF_PUD": 1
    },
    "redFlagFor": [
      "PERF_PUD"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=천공성 소화성 궤양; source=#73 천공성 소화성 궤양 / 앱 체크리스트 키: sudden epigastric; peritonitis; free air; CT"
  },
  {
    "id": "AK-064",
    "labelKo": "pulse deficit",
    "category": "physical",
    "weights": {
      "DIS": 1
    },
    "redFlagFor": [
      "DIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=급성 대동맥 박리; source=#8 급성 대동맥 박리 / 앱 체크리스트 키: abrupt tearing; pulse deficit; neuro; CTA aorta"
  },
  {
    "id": "AK-065",
    "labelKo": "pulsus",
    "category": "physical",
    "weights": {
      "TAMPONADE": 1
    },
    "redFlagFor": [
      "TAMPONADE"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=심장압전 독립 게이트; source=#63 심장압전 독립 게이트 / 앱 체크리스트 키: hypotension; JVD; pulsus; POCUS/echo"
  },
  {
    "id": "AK-066",
    "labelKo": "unilateral breath sound",
    "category": "physical",
    "weights": {
      "TPTX": 1
    },
    "redFlagFor": [
      "TPTX"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=긴장성 기흉; source=#20 긴장성 기흉 / 앱 체크리스트 키: unilateral breath sound; shock; immediate decompression"
  },
  {
    "id": "AK-067",
    "labelKo": "crackles",
    "category": "physical",
    "weights": {
      "AHF": 1,
      "PNA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=급성 심부전 / 폐부종; 폐렴; source=#12 급성 심부전 / 폐부종 / 앱 체크리스트 키: dyspnea; crackles; BNP; CXR/POCUS --- #23 폐렴 / 앱 체크리스트 키: fever cough sputum; crackles; CXR"
  },
  {
    "id": "AK-068",
    "labelKo": "Murphy",
    "category": "physical",
    "weights": {
      "CHOLE": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=급성 담낭염; source=#39 급성 담낭염 / 앱 체크리스트 키: RUQ pain; Murphy; fever; US; Tokyo criteria"
  },
  {
    "id": "AK-069",
    "labelKo": "SC joint swelling",
    "category": "physical",
    "weights": {
      "SC_JOINT_INFECTION": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=흉쇄관절 감염 / 골수염; source=#82 흉쇄관절 감염 / 골수염 / 앱 체크리스트 키: SC joint swelling; fever; IVDU/diabetes; CT/MRI/culture"
  },
  {
    "id": "AK-070",
    "labelKo": "back tenderness",
    "category": "physical",
    "weights": {
      "THORACIC_COMPRESSION_FX": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=흉추 압박골절; source=#80 흉추 압박골절 / 앱 체크리스트 키: elderly/osteoporosis; back tenderness; spine imaging"
  },
  {
    "id": "AK-071",
    "labelKo": "breast redness/mass",
    "category": "physical",
    "weights": {
      "MASTITIS_MONDOR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=유방/흉벽 감염 또는 Mondor disease; source=#87 유방/흉벽 감염 또는 Mondor disease / 앱 체크리스트 키: breast redness/mass; lactation; cord; US"
  },
  {
    "id": "AK-072",
    "labelKo": "click/murmur",
    "category": "physical",
    "weights": {
      "MVP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=승모판 탈출증; source=#14 승모판 탈출증 / 앱 체크리스트 키: click/murmur; palpitations; TTE"
  },
  {
    "id": "AK-073",
    "labelKo": "clicking",
    "category": "physical",
    "weights": {
      "SLIPPING_RIB": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=갈비뼈 미끄럼 증후군; source=#81 갈비뼈 미끄럼 증후군 / 앱 체크리스트 키: lower rib pain; clicking; hooking maneuver"
  },
  {
    "id": "AK-074",
    "labelKo": "cord",
    "category": "physical",
    "weights": {
      "MASTITIS_MONDOR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=유방/흉벽 감염 또는 Mondor disease; source=#87 유방/흉벽 감염 또는 Mondor disease / 앱 체크리스트 키: breast redness/mass; lactation; cord; US"
  },
  {
    "id": "AK-075",
    "labelKo": "decreased breath sound",
    "category": "physical",
    "weights": {
      "PLEFF": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=흉막삼출; source=#25 흉막삼출 / 앱 체크리스트 키: dullness; decreased breath sound; US; thoracentesis"
  },
  {
    "id": "AK-076",
    "labelKo": "ecchymosis",
    "category": "physical",
    "weights": {
      "CHEST_CONTUSION": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=흉벽 타박상 / 외상 후 흉통; source=#47 흉벽 타박상 / 외상 후 흉통 / 앱 체크리스트 키: trauma; ecchymosis; eFAST/CXR/CT"
  },
  {
    "id": "AK-077",
    "labelKo": "focal tenderness",
    "category": "physical",
    "weights": {
      "RIB": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=늑골골절; source=#46 늑골골절 / 앱 체크리스트 키: trauma/CPR/cough; focal tenderness; CXR/CT"
  },
  {
    "id": "AK-078",
    "labelKo": "hooking maneuver",
    "category": "physical",
    "weights": {
      "SLIPPING_RIB": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=갈비뼈 미끄럼 증후군; source=#81 갈비뼈 미끄럼 증후군 / 앱 체크리스트 키: lower rib pain; clicking; hooking maneuver"
  },
  {
    "id": "AK-079",
    "labelKo": "localized swelling",
    "category": "physical",
    "weights": {
      "TIETZE": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=Tietze 증후군; source=#44 Tietze 증후군 / 앱 체크리스트 키: localized swelling; tenderness"
  },
  {
    "id": "AK-080",
    "labelKo": "neuro deficit",
    "category": "physical",
    "weights": {
      "CRAD_TRAD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=경추 또는 흉추 신경근병증; source=#49 경추 또는 흉추 신경근병증 / 앱 체크리스트 키: neck/back movement; neuro deficit; MRI"
  },
  {
    "id": "AK-081",
    "labelKo": "neuropathic",
    "category": "physical",
    "weights": {
      "ICN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=늑간신경통; source=#48 늑간신경통 / 앱 체크리스트 키: dermatomal; neuropathic; zoster/trauma"
  },
  {
    "id": "AK-082",
    "labelKo": "paradoxical movement",
    "category": "physical",
    "weights": {
      "PULM_CONTUSION_FLAIL": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=폐좌상 / 동요흉; source=#89 폐좌상 / 동요흉 / 앱 체크리스트 키: blunt trauma; hypoxia; CT/CXR; paradoxical movement"
  },
  {
    "id": "AK-083",
    "labelKo": "reproducible tenderness",
    "category": "physical",
    "weights": {
      "COSTO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=늑연골염; source=#43 늑연골염 / 앱 체크리스트 키: reproducible tenderness; movement; no red flag"
  },
  {
    "id": "AK-084",
    "labelKo": "systolic murmur",
    "category": "physical",
    "weights": {
      "AS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=대동맥판 협착; source=#13 대동맥판 협착 / 앱 체크리스트 키: exertional chest pain/syncope; systolic murmur; TTE"
  },
  {
    "id": "AK-085",
    "labelKo": "tenderness",
    "category": "physical",
    "weights": {
      "TIETZE": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=Tietze 증후군; source=#44 Tietze 증후군 / 앱 체크리스트 키: localized swelling; tenderness"
  },
  {
    "id": "AK-086",
    "labelKo": "vesicles",
    "category": "physical",
    "weights": {
      "ZOSTER": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=대상포진; source=#50 대상포진 / 앱 체크리스트 키: dermatomal pain; vesicles; immunosuppression"
  },
  {
    "id": "AK-087",
    "labelKo": "wheeze",
    "category": "physical",
    "weights": {
      "ASTHMA_EXAC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=천식 급성 악화; source=#28 천식 급성 악화 / 앱 체크리스트 키: wheeze; PEF; response to bronchodilator"
  },
  {
    "id": "AK-088",
    "labelKo": "xiphoid focal tenderness",
    "category": "physical",
    "weights": {
      "XIPHO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=신체진찰; related=검상돌기통; source=#83 검상돌기통 / 앱 체크리스트 키: xiphoid focal tenderness; reproducible"
  },
  {
    "id": "AK-089",
    "labelKo": "LFT",
    "category": "lab",
    "weights": {
      "CHOLANG": 1
    },
    "redFlagFor": [
      "CHOLANG"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=담관염; source=#40 담관염 / 앱 체크리스트 키: fever jaundice RUQ; LFT; biliary dilation; drainage"
  },
  {
    "id": "AK-090",
    "labelKo": "serial ECG/troponin",
    "category": "ecg",
    "weights": {
      "UA": 1
    },
    "redFlagFor": [
      "UA"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=불안정 협심증 / ACS; source=#3 불안정 협심증 / ACS / 앱 체크리스트 키: new/worsening/rest angina; serial ECG/troponin"
  },
  {
    "id": "AK-091",
    "labelKo": "serial hs-cTn",
    "category": "lab",
    "weights": {
      "NSTEMI": 1
    },
    "redFlagFor": [
      "NSTEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=비ST분절상승 심근경색; source=#2 비ST분절상승 심근경색 / 앱 체크리스트 키: serial hs-cTn; ECG dynamic change; GRACE/HEART"
  },
  {
    "id": "AK-092",
    "labelKo": "serial troponin",
    "category": "lab",
    "weights": {
      "STEMI": 1
    },
    "redFlagFor": [
      "STEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=ST분절상승 심근경색; source=#1 ST분절상승 심근경색 / 앱 체크리스트 키: ECG; serial troponin; ACS risk; radiation; diaphoresis"
  },
  {
    "id": "AK-093",
    "labelKo": "ABG",
    "category": "lab",
    "weights": {
      "COPD_EXAC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=COPD 급성 악화; source=#29 COPD 급성 악화 / 앱 체크리스트 키: COPD history; sputum; ABG; CXR"
  },
  {
    "id": "AK-094",
    "labelKo": "AFB/ADA",
    "category": "lab",
    "weights": {
      "TB_PLEURITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=결핵성 흉막염 / 폐결핵; source=#68 결핵성 흉막염 / 폐결핵 / 앱 체크리스트 키: weight loss/night sweat; TB exposure; effusion; AFB/ADA"
  },
  {
    "id": "AK-095",
    "labelKo": "BNP",
    "category": "lab",
    "weights": {
      "AHF": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=급성 심부전 / 폐부종; source=#12 급성 심부전 / 폐부종 / 앱 체크리스트 키: dyspnea; crackles; BNP; CXR/POCUS"
  },
  {
    "id": "AK-096",
    "labelKo": "COHb/troponin",
    "category": "lab",
    "weights": {
      "CO_POISONING_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=일산화탄소 중독 관련 심근허혈; source=#86 일산화탄소 중독 관련 심근허혈 / 앱 체크리스트 키: CO exposure; headache; multiple patients; COHb/troponin"
  },
  {
    "id": "AK-097",
    "labelKo": "ECG/troponin",
    "category": "ecg",
    "weights": {
      "STIMULANT_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=자극제 관련 관상동맥 허혈/연축; source=#61 자극제 관련 관상동맥 허혈/연축 / 앱 체크리스트 키: stimulant use; hypertension/tachy; ECG/troponin"
  },
  {
    "id": "AK-098",
    "labelKo": "ECG/troponin/renal/neuro",
    "category": "ecg",
    "weights": {
      "HTN_EMERG": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=고혈압 응급증 관련 흉통; source=#18 고혈압 응급증 관련 흉통 / 앱 체크리스트 키: severe BP; organ damage; ECG/troponin/renal/neuro"
  },
  {
    "id": "AK-099",
    "labelKo": "PCR",
    "category": "lab",
    "weights": {
      "VIRAL_PNA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=바이러스 폐렴 / COVID-19 / 인플루엔자; source=#70 바이러스 폐렴 / COVID-19 / 인플루엔자 / 앱 체크리스트 키: viral syndrome; exposure; PCR; CXR"
  },
  {
    "id": "AK-100",
    "labelKo": "VBG",
    "category": "lab",
    "weights": {
      "HVS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=과호흡증후군; source=#55 과호흡증후군 / 앱 체크리스트 키: tachypnea; paresthesia; VBG; after rule-out"
  },
  {
    "id": "AK-101",
    "labelKo": "electrolytes",
    "category": "lab",
    "weights": {
      "ARR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=부정맥 관련 흉통; source=#16 부정맥 관련 흉통 / 앱 체크리스트 키: palpitation; syncope; ECG monitor; electrolytes"
  },
  {
    "id": "AK-102",
    "labelKo": "headache",
    "category": "lab",
    "weights": {
      "CO_POISONING_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=일산화탄소 중독 관련 심근허혈; source=#86 일산화탄소 중독 관련 심근허혈 / 앱 체크리스트 키: CO exposure; headache; multiple patients; COHb/troponin"
  },
  {
    "id": "AK-103",
    "labelKo": "lipase",
    "category": "lab",
    "weights": {
      "PANC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=급성 췌장염; source=#41 급성 췌장염 / 앱 체크리스트 키: epigastric to back; lipase; alcohol/gallstone"
  },
  {
    "id": "AK-104",
    "labelKo": "troponin",
    "category": "lab",
    "weights": {
      "MYO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=심근염; source=#11 심근염 / 앱 체크리스트 키: viral prodrome; troponin; arrhythmia; echo/CMR"
  },
  {
    "id": "AK-105",
    "labelKo": "troponin rise/fall",
    "category": "lab",
    "weights": {
      "T2MI": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=ECG/혈액/검사; related=2형 심근경색; source=#58 2형 심근경색 / 앱 체크리스트 키: troponin rise/fall; anemia/hypoxia/sepsis/tachy"
  },
  {
    "id": "AK-106",
    "labelKo": "CTA",
    "category": "thoracic_imaging",
    "weights": {
      "TAA": 1,
      "TRAUMATIC_AORTIC_INJURY": 1
    },
    "redFlagFor": [
      "TAA",
      "TRAUMATIC_AORTIC_INJURY"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=흉부 대동맥류 파열 또는 누출; 외상성 대혈관 손상; source=#9 흉부 대동맥류 파열 또는 누출 / 앱 체크리스트 키: known aneurysm; sudden back/chest pain; CTA --- #88 외상성 대혈관 손상 / 앱 체크리스트 키: high-energy trauma; widened mediastinum; CTA"
  },
  {
    "id": "AK-107",
    "labelKo": "CTPA",
    "category": "thoracic_imaging",
    "weights": {
      "PE": 1,
      "PULM_INFARCT": 1
    },
    "redFlagFor": [
      "PE",
      "PULM_INFARCT"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=폐색전증; 폐경색; source=#19 폐색전증 / 앱 체크리스트 키: pleuritic pain; dyspnea; DVT; Wells/PERC/D-dimer; CTPA --- #26 폐경색 / 앱 체크리스트 키: PE symptoms; hemoptysis; wedge opacity; CTPA"
  },
  {
    "id": "AK-108",
    "labelKo": "eFAST/CXR/CT",
    "category": "thoracic_imaging",
    "weights": {
      "TRAUMATIC_PTX_HEMOTHORAX": 1,
      "CHEST_CONTUSION": 1
    },
    "redFlagFor": [
      "TRAUMATIC_PTX_HEMOTHORAX",
      "CHEST_CONTUSION"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=외상성 기흉 / 혈흉; 흉벽 타박상 / 외상 후 흉통; source=#22 외상성 기흉 / 혈흉 / 앱 체크리스트 키: trauma; breath sound; eFAST/CXR/CT --- #47 흉벽 타박상 / 외상 후 흉통 / 앱 체크리스트 키: trauma; ecchymosis; eFAST/CXR/CT"
  },
  {
    "id": "AK-109",
    "labelKo": "CT esophagram",
    "category": "thoracic_imaging",
    "weights": {
      "BOER": 1
    },
    "redFlagFor": [
      "BOER"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=식도파열; source=#34 식도파열 / 앱 체크리스트 키: vomiting before pain; subcutaneous emphysema; CT esophagram"
  },
  {
    "id": "AK-110",
    "labelKo": "CT mediastinum",
    "category": "thoracic_imaging",
    "weights": {
      "MEDIASTINITIS": 1
    },
    "redFlagFor": [
      "MEDIASTINITIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=종격동염; source=#72 종격동염 / 앱 체크리스트 키: esophageal rupture; post-op; fever sepsis; CT mediastinum"
  },
  {
    "id": "AK-111",
    "labelKo": "CTA aorta",
    "category": "thoracic_imaging",
    "weights": {
      "DIS": 1
    },
    "redFlagFor": [
      "DIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=급성 대동맥 박리; source=#8 급성 대동맥 박리 / 앱 체크리스트 키: abrupt tearing; pulse deficit; neuro; CTA aorta"
  },
  {
    "id": "AK-112",
    "labelKo": "CTA protocol",
    "category": "thoracic_imaging",
    "weights": {
      "AAS_IMH_PAU": 1
    },
    "redFlagFor": [
      "AAS_IMH_PAU"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=급성 대동맥 증후군: 벽내혈종/관통성 궤양; source=#59 급성 대동맥 증후군: 벽내혈종/관통성 궤양 / 앱 체크리스트 키: abrupt back pain; aortic risk; CTA protocol"
  },
  {
    "id": "AK-113",
    "labelKo": "POCUS/echo",
    "category": "cardiac_imaging",
    "weights": {
      "TAMPONADE": 1
    },
    "redFlagFor": [
      "TAMPONADE"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=심장압전 독립 게이트; source=#63 심장압전 독립 게이트 / 앱 체크리스트 키: hypotension; JVD; pulsus; POCUS/echo"
  },
  {
    "id": "AK-114",
    "labelKo": "angiography",
    "category": "thoracic_imaging",
    "weights": {
      "SCAD": 1
    },
    "redFlagFor": [
      "SCAD"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=자발성 관상동맥 박리; source=#7 자발성 관상동맥 박리 / 앱 체크리스트 키: young female ACS; postpartum; FMD; angiography"
  },
  {
    "id": "AK-115",
    "labelKo": "echo",
    "category": "cardiac_imaging",
    "weights": {
      "PERI": 1
    },
    "redFlagFor": [
      "PERI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=심낭염 / 심낭삼출 / 심장압전; source=#10 심낭염 / 심낭삼출 / 심장압전 / 앱 체크리스트 키: pleuritic/positional; rub; diffuse ST/PR; echo"
  },
  {
    "id": "AK-116",
    "labelKo": "CXR",
    "category": "thoracic_imaging",
    "weights": {
      "PNA": 1,
      "COPD_EXAC": 1,
      "VIRAL_PNA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=폐렴; COPD 급성 악화; 바이러스 폐렴 / COVID-19 / 인플루엔자; source=#23 폐렴 / 앱 체크리스트 키: fever cough sputum; crackles; CXR --- #29 COPD 급성 악화 / 앱 체크리스트 키: COPD history; sputum; ABG; CXR --- #70 바이러스 폐렴 / COVID-19 / 인플루엔자 / 앱 체크리스트 키: viral syndrome; exposure; PCR; CXR"
  },
  {
    "id": "AK-117",
    "labelKo": "EGD",
    "category": "gi_test",
    "weights": {
      "ESOPH": 1,
      "MALLORY_WEISS": 1,
      "PUD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=식도염; Mallory-Weiss tear; 소화성 궤양; source=#32 식도염 / 앱 체크리스트 키: odynophagia; dysphagia; immunocompromise; EGD --- #35 Mallory-Weiss tear / 앱 체크리스트 키: vomiting + hematemesis; EGD --- #36 소화성 궤양 / 앱 체크리스트 키: epigastric burning; NSAID; melena; EGD"
  },
  {
    "id": "AK-118",
    "labelKo": "EGD biopsy",
    "category": "gi_test",
    "weights": {
      "PILL_INFECTIOUS_EOE_ESOPHAGITIS": 1,
      "ESOPHAGEAL_CANCER": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=약제성/감염성/호산구성 식도염; 식도암; source=#75 약제성/감염성/호산구성 식도염 / 앱 체크리스트 키: pill history; odynophagia; immunocompromise; EGD biopsy --- #76 식도암 / 앱 체크리스트 키: progressive dysphagia; weight loss; EGD biopsy"
  },
  {
    "id": "AK-119",
    "labelKo": "TTE",
    "category": "thoracic_imaging",
    "weights": {
      "AS": 1,
      "MVP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=대동맥판 협착; 승모판 탈출증; source=#13 대동맥판 협착 / 앱 체크리스트 키: exertional chest pain/syncope; systolic murmur; TTE --- #14 승모판 탈출증 / 앱 체크리스트 키: click/murmur; palpitations; TTE"
  },
  {
    "id": "AK-120",
    "labelKo": "echo/CMR",
    "category": "cardiac_imaging",
    "weights": {
      "MYO": 1,
      "HCM": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=심근염; 비후성 심근병증; source=#11 심근염 / 앱 체크리스트 키: viral prodrome; troponin; arrhythmia; echo/CMR --- #15 비후성 심근병증 / 앱 체크리스트 키: young exertional; syncope; family sudden death; echo/CMR"
  },
  {
    "id": "AK-121",
    "labelKo": "manometry",
    "category": "thoracic_imaging",
    "weights": {
      "ESPASM": 1,
      "ACHALASIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=식도경련 / 식도운동장애; 이완불능증; source=#33 식도경련 / 식도운동장애 / 앱 체크리스트 키: dysphagia; temperature trigger; manometry --- #74 이완불능증 / 앱 체크리스트 키: solid+liquid dysphagia; regurgitation; manometry"
  },
  {
    "id": "AK-122",
    "labelKo": "CCTA coronary anatomy",
    "category": "thoracic_imaging",
    "weights": {
      "ANOMALOUS_CORONARY": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=선천성 관상동맥 이상 / 심근교; source=#65 선천성 관상동맥 이상 / 심근교 / 앱 체크리스트 키: young exertional; syncope; CCTA coronary anatomy"
  },
  {
    "id": "AK-123",
    "labelKo": "CCTA/stress test",
    "category": "thoracic_imaging",
    "weights": {
      "SA_CCD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=안정형 협심증; source=#4 안정형 협심증 / 앱 체크리스트 키: exertional; rest relief; CCTA/stress test"
  },
  {
    "id": "AK-124",
    "labelKo": "CMR/OCT",
    "category": "cardiac_imaging",
    "weights": {
      "MINOCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=MINOCA; source=#62 MINOCA / 앱 체크리스트 키: MI + nonobstructive coronaries; CMR/OCT"
  },
  {
    "id": "AK-125",
    "labelKo": "CT abdomen",
    "category": "thoracic_imaging",
    "weights": {
      "SPLENIC_INFARCT": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=비장경색; source=#78 비장경색 / 앱 체크리스트 키: LUQ/left chest; AF/IE; CT abdomen"
  },
  {
    "id": "AK-126",
    "labelKo": "CT cavity",
    "category": "thoracic_imaging",
    "weights": {
      "LUNG_ABSCESS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=폐농양; source=#71 폐농양 / 앱 체크리스트 키: subacute fever; foul sputum; CT cavity"
  },
  {
    "id": "AK-127",
    "labelKo": "CT/CXR",
    "category": "thoracic_imaging",
    "weights": {
      "PULM_CONTUSION_FLAIL": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=폐좌상 / 동요흉; source=#89 폐좌상 / 동요흉 / 앱 체크리스트 키: blunt trauma; hypoxia; CT/CXR; paradoxical movement"
  },
  {
    "id": "AK-128",
    "labelKo": "CT/MRI/culture",
    "category": "thoracic_imaging",
    "weights": {
      "SC_JOINT_INFECTION": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=흉쇄관절 감염 / 골수염; source=#82 흉쇄관절 감염 / 골수염 / 앱 체크리스트 키: SC joint swelling; fever; IVDU/diabetes; CT/MRI/culture"
  },
  {
    "id": "AK-129",
    "labelKo": "CT/barium/EGD",
    "category": "gi_test",
    "weights": {
      "HH": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=열공탈장; source=#42 열공탈장 / 앱 체크리스트 키: postprandial; reflux; dysphagia; CT/barium/EGD"
  },
  {
    "id": "AK-130",
    "labelKo": "CXR/CT",
    "category": "thoracic_imaging",
    "weights": {
      "RIB": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=늑골골절; source=#46 늑골골절 / 앱 체크리스트 키: trauma/CPR/cough; focal tenderness; CXR/CT"
  },
  {
    "id": "AK-131",
    "labelKo": "CXR/PE screen",
    "category": "thoracic_imaging",
    "weights": {
      "PLEUR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=흉막염; source=#24 흉막염 / 앱 체크리스트 키: pleuritic pain; rub; CXR/PE screen"
  },
  {
    "id": "AK-132",
    "labelKo": "CXR/POCUS",
    "category": "thoracic_imaging",
    "weights": {
      "AHF": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=급성 심부전 / 폐부종; source=#12 급성 심부전 / 폐부종 / 앱 체크리스트 키: dyspnea; crackles; BNP; CXR/POCUS"
  },
  {
    "id": "AK-133",
    "labelKo": "CXR/US",
    "category": "thoracic_imaging",
    "weights": {
      "PTX": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=자연기흉; source=#21 자연기흉 / 앱 체크리스트 키: sudden unilateral; tall thin/smoking; CXR/US"
  },
  {
    "id": "AK-134",
    "labelKo": "H pylori/EGD",
    "category": "gi_test",
    "weights": {
      "DYSPEP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=위염 / 기능성 소화불량; source=#37 위염 / 기능성 소화불량 / 앱 체크리스트 키: epigastric; alarm symptoms; H pylori/EGD"
  },
  {
    "id": "AK-135",
    "labelKo": "MRI",
    "category": "thoracic_imaging",
    "weights": {
      "CRAD_TRAD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=경추 또는 흉추 신경근병증; source=#49 경추 또는 흉추 신경근병증 / 앱 체크리스트 키: neck/back movement; neuro deficit; MRI"
  },
  {
    "id": "AK-136",
    "labelKo": "duplex/CTA",
    "category": "thoracic_imaging",
    "weights": {
      "TOS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=흉곽출구증후군; source=#52 흉곽출구증후군 / 앱 체크리스트 키: arm symptoms; overhead; vascular signs; duplex/CTA"
  },
  {
    "id": "AK-137",
    "labelKo": "echo apical ballooning",
    "category": "cardiac_imaging",
    "weights": {
      "TTS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=스트레스성 심근병증; source=#17 스트레스성 심근병증 / 앱 체크리스트 키: stress trigger; postmenopausal; echo apical ballooning; ACS rule-out"
  },
  {
    "id": "AK-138",
    "labelKo": "echo/RHC",
    "category": "cardiac_imaging",
    "weights": {
      "PH_RV_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=폐고혈압 / 우심실 허혈; source=#64 폐고혈압 / 우심실 허혈 / 앱 체크리스트 키: exertional syncope; RV signs; echo/RHC"
  },
  {
    "id": "AK-139",
    "labelKo": "echo/TEE",
    "category": "cardiac_imaging",
    "weights": {
      "CORONARY_EMBOLISM": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=관상동맥 색전/혈전증; source=#60 관상동맥 색전/혈전증 / 앱 체크리스트 키: AF/valve/IE; ACS with low CAD risk; echo/TEE"
  },
  {
    "id": "AK-140",
    "labelKo": "lactation",
    "category": "thoracic_imaging",
    "weights": {
      "MASTITIS_MONDOR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=유방/흉벽 감염 또는 Mondor disease; source=#87 유방/흉벽 감염 또는 Mondor disease / 앱 체크리스트 키: breast redness/mass; lactation; cord; US"
  },
  {
    "id": "AK-141",
    "labelKo": "normal CXR after red flags",
    "category": "thoracic_imaging",
    "weights": {
      "VIRAL_PLEURITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=바이러스성 흉막염 / 유행성 흉통; source=#67 바이러스성 흉막염 / 유행성 흉통 / 앱 체크리스트 키: URI prodrome; pleuritic; normal CXR after red flags"
  },
  {
    "id": "AK-142",
    "labelKo": "stimulant use",
    "category": "thoracic_imaging",
    "weights": {
      "STIMULANT_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=자극제 관련 관상동맥 허혈/연축; source=#61 자극제 관련 관상동맥 허혈/연축 / 앱 체크리스트 키: stimulant use; hypertension/tachy; ECG/troponin"
  },
  {
    "id": "AK-143",
    "labelKo": "ultrasound/LFT",
    "category": "thoracic_imaging",
    "weights": {
      "BILCOL": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=영상/시술/확진; related=담석증 / 담도산통; source=#38 담석증 / 담도산통 / 앱 체크리스트 키: RUQ/epigastric; fatty meal; ultrasound/LFT"
  },
  {
    "id": "AK-144",
    "labelKo": "GRACE/HEART",
    "category": "history",
    "weights": {
      "NSTEMI": 1
    },
    "redFlagFor": [
      "NSTEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=비ST분절상승 심근경색; source=#2 비ST분절상승 심근경색 / 앱 체크리스트 키: serial hs-cTn; ECG dynamic change; GRACE/HEART"
  },
  {
    "id": "AK-145",
    "labelKo": "Wells/PERC/D-dimer",
    "category": "history",
    "weights": {
      "PE": 1
    },
    "redFlagFor": [
      "PE"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=폐색전증; source=#19 폐색전증 / 앱 체크리스트 키: pleuritic pain; dyspnea; DVT; Wells/PERC/D-dimer; CTPA"
  },
  {
    "id": "AK-146",
    "labelKo": "fever sepsis",
    "category": "history",
    "weights": {
      "MEDIASTINITIS": 1
    },
    "redFlagFor": [
      "MEDIASTINITIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=종격동염; source=#72 종격동염 / 앱 체크리스트 키: esophageal rupture; post-op; fever sepsis; CT mediastinum"
  },
  {
    "id": "AK-147",
    "labelKo": "Rome",
    "category": "history",
    "weights": {
      "FCP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=기능성 흉통; source=#56 기능성 흉통 / 앱 체크리스트 키: noncardiac recurrent; normal workup; Rome"
  },
  {
    "id": "AK-148",
    "labelKo": "Tokyo criteria",
    "category": "history",
    "weights": {
      "CHOLE": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=급성 담낭염; source=#39 급성 담낭염 / 앱 체크리스트 키: RUQ pain; Murphy; fever; US; Tokyo criteria"
  },
  {
    "id": "AK-149",
    "labelKo": "URI prodrome",
    "category": "history",
    "weights": {
      "VIRAL_PLEURITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=바이러스성 흉막염 / 유행성 흉통; source=#67 바이러스성 흉막염 / 유행성 흉통 / 앱 체크리스트 키: URI prodrome; pleuritic; normal CXR after red flags"
  },
  {
    "id": "AK-150",
    "labelKo": "anemia/hypoxia/sepsis/tachy",
    "category": "history",
    "weights": {
      "T2MI": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=2형 심근경색; source=#58 2형 심근경색 / 앱 체크리스트 키: troponin rise/fall; anemia/hypoxia/sepsis/tachy"
  },
  {
    "id": "AK-151",
    "labelKo": "heartburn",
    "category": "history",
    "weights": {
      "GERD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=위식도역류질환; source=#31 위식도역류질환 / 앱 체크리스트 키: heartburn; regurgitation; meal/lying; alarm symptoms"
  },
  {
    "id": "AK-152",
    "labelKo": "viral prodrome",
    "category": "history",
    "weights": {
      "MYO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=심근염; source=#11 심근염 / 앱 체크리스트 키: viral prodrome; troponin; arrhythmia; echo/CMR"
  },
  {
    "id": "AK-153",
    "labelKo": "viral syndrome",
    "category": "history",
    "weights": {
      "VIRAL_PNA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=Score/기준; related=바이러스 폐렴 / COVID-19 / 인플루엔자; source=#70 바이러스 폐렴 / COVID-19 / 인플루엔자 / 앱 체크리스트 키: viral syndrome; exposure; PCR; CXR"
  },
  {
    "id": "AK-154",
    "labelKo": "fever jaundice RUQ",
    "category": "gi_test",
    "weights": {
      "CHOLANG": 1
    },
    "redFlagFor": [
      "CHOLANG"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=담관염; source=#40 담관염 / 앱 체크리스트 키: fever jaundice RUQ; LFT; biliary dilation; drainage"
  },
  {
    "id": "AK-155",
    "labelKo": "sudden epigastric",
    "category": "gi_test",
    "weights": {
      "PERF_PUD": 1
    },
    "redFlagFor": [
      "PERF_PUD"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=천공성 소화성 궤양; source=#73 천공성 소화성 궤양 / 앱 체크리스트 키: sudden epigastric; peritonitis; free air; CT"
  },
  {
    "id": "AK-156",
    "labelKo": "vomiting before pain",
    "category": "gi_test",
    "weights": {
      "BOER": 1
    },
    "redFlagFor": [
      "BOER"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=식도파열; source=#34 식도파열 / 앱 체크리스트 키: vomiting before pain; subcutaneous emphysema; CT esophagram"
  },
  {
    "id": "AK-157",
    "labelKo": "dysphagia",
    "category": "gi_test",
    "weights": {
      "ESOPH": 1,
      "ESPASM": 1,
      "HH": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=식도염; 식도경련 / 식도운동장애; 열공탈장; source=#32 식도염 / 앱 체크리스트 키: odynophagia; dysphagia; immunocompromise; EGD --- #33 식도경련 / 식도운동장애 / 앱 체크리스트 키: dysphagia; temperature trigger; manometry --- #42 열공탈장 / 앱 체크리스트 키: postprandial; reflux; dysphagia; CT/barium/EGD"
  },
  {
    "id": "AK-158",
    "labelKo": "odynophagia",
    "category": "gi_test",
    "weights": {
      "ESOPH": 1,
      "PILL_INFECTIOUS_EOE_ESOPHAGITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=식도염; 약제성/감염성/호산구성 식도염; source=#32 식도염 / 앱 체크리스트 키: odynophagia; dysphagia; immunocompromise; EGD --- #75 약제성/감염성/호산구성 식도염 / 앱 체크리스트 키: pill history; odynophagia; immunocompromise; EGD biopsy"
  },
  {
    "id": "AK-159",
    "labelKo": "regurgitation",
    "category": "gi_test",
    "weights": {
      "GERD": 1,
      "ACHALASIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=위식도역류질환; 이완불능증; source=#31 위식도역류질환 / 앱 체크리스트 키: heartburn; regurgitation; meal/lying; alarm symptoms --- #74 이완불능증 / 앱 체크리스트 키: solid+liquid dysphagia; regurgitation; manometry"
  },
  {
    "id": "AK-160",
    "labelKo": "RUQ pain",
    "category": "gi_test",
    "weights": {
      "CHOLE": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=급성 담낭염; source=#39 급성 담낭염 / 앱 체크리스트 키: RUQ pain; Murphy; fever; US; Tokyo criteria"
  },
  {
    "id": "AK-161",
    "labelKo": "RUQ/epigastric",
    "category": "gi_test",
    "weights": {
      "BILCOL": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=담석증 / 담도산통; source=#38 담석증 / 담도산통 / 앱 체크리스트 키: RUQ/epigastric; fatty meal; ultrasound/LFT"
  },
  {
    "id": "AK-162",
    "labelKo": "RUQ/shoulder",
    "category": "gi_test",
    "weights": {
      "SUBPHRENIC_ABSCESS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=횡격막하 농양 / 간농양; source=#79 횡격막하 농양 / 간농양 / 앱 체크리스트 키: fever; RUQ/shoulder; post-op; CT/US"
  },
  {
    "id": "AK-163",
    "labelKo": "epigastric",
    "category": "gi_test",
    "weights": {
      "DYSPEP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=위염 / 기능성 소화불량; source=#37 위염 / 기능성 소화불량 / 앱 체크리스트 키: epigastric; alarm symptoms; H pylori/EGD"
  },
  {
    "id": "AK-164",
    "labelKo": "epigastric burning",
    "category": "gi_test",
    "weights": {
      "PUD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=소화성 궤양; source=#36 소화성 궤양 / 앱 체크리스트 키: epigastric burning; NSAID; melena; EGD"
  },
  {
    "id": "AK-165",
    "labelKo": "epigastric to back",
    "category": "gi_test",
    "weights": {
      "PANC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=급성 췌장염; source=#41 급성 췌장염 / 앱 체크리스트 키: epigastric to back; lipase; alcohol/gallstone"
  },
  {
    "id": "AK-166",
    "labelKo": "fatty meal",
    "category": "gi_test",
    "weights": {
      "BILCOL": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=담석증 / 담도산통; source=#38 담석증 / 담도산통 / 앱 체크리스트 키: RUQ/epigastric; fatty meal; ultrasound/LFT"
  },
  {
    "id": "AK-167",
    "labelKo": "melena",
    "category": "gi_test",
    "weights": {
      "PUD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=소화성 궤양; source=#36 소화성 궤양 / 앱 체크리스트 키: epigastric burning; NSAID; melena; EGD"
  },
  {
    "id": "AK-168",
    "labelKo": "progressive dysphagia",
    "category": "gi_test",
    "weights": {
      "ESOPHAGEAL_CANCER": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=식도암; source=#76 식도암 / 앱 체크리스트 키: progressive dysphagia; weight loss; EGD biopsy"
  },
  {
    "id": "AK-169",
    "labelKo": "severe epigastric/chest",
    "category": "gi_test",
    "weights": {
      "GASTRIC_VOLVULUS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=위염전 / 위확장; source=#77 위염전 / 위확장 / 앱 체크리스트 키: severe epigastric/chest; retching; NG failure; CT"
  },
  {
    "id": "AK-170",
    "labelKo": "solid+liquid dysphagia",
    "category": "gi_test",
    "weights": {
      "ACHALASIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=이완불능증; source=#74 이완불능증 / 앱 체크리스트 키: solid+liquid dysphagia; regurgitation; manometry"
  },
  {
    "id": "AK-171",
    "labelKo": "vomiting",
    "category": "gi_test",
    "weights": {
      "STRANGULATED_HERNIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=감돈/교액성 식도열공·횡격막 탈장; source=#90 감돈/교액성 식도열공·횡격막 탈장 / 앱 체크리스트 키: postprandial severe pain; vomiting; hernia history; CT"
  },
  {
    "id": "AK-172",
    "labelKo": "vomiting + hematemesis",
    "category": "gi_test",
    "weights": {
      "MALLORY_WEISS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=Mallory-Weiss tear; source=#35 Mallory-Weiss tear / 앱 체크리스트 키: vomiting + hematemesis; EGD"
  },
  {
    "id": "AK-173",
    "labelKo": "vomiting/asthma",
    "category": "gi_test",
    "weights": {
      "PMED": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=위장관/식도; related=종격동기종 / 기종격; source=#27 종격동기종 / 기종격 / 앱 체크리스트 키: subcutaneous emphysema; vomiting/asthma; CT"
  },
  {
    "id": "AK-174",
    "labelKo": "reproducible",
    "category": "msk_neuro_skin",
    "weights": {
      "STRAIN": 1,
      "XIPHO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=근골격/신경/흉벽; related=흉벽 근육통 / 근육염좌; 검상돌기통; source=#45 흉벽 근육통 / 근육염좌 / 앱 체크리스트 키: movement-related; reproducible; trauma/exertion --- #83 검상돌기통 / 앱 체크리스트 키: xiphoid focal tenderness; reproducible"
  },
  {
    "id": "AK-175",
    "labelKo": "dermatomal",
    "category": "msk_neuro_skin",
    "weights": {
      "ICN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=근골격/신경/흉벽; related=늑간신경통; source=#48 늑간신경통 / 앱 체크리스트 키: dermatomal; neuropathic; zoster/trauma"
  },
  {
    "id": "AK-176",
    "labelKo": "dermatomal pain",
    "category": "msk_neuro_skin",
    "weights": {
      "ZOSTER": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=근골격/신경/흉벽; related=대상포진; source=#50 대상포진 / 앱 체크리스트 키: dermatomal pain; vesicles; immunosuppression"
  },
  {
    "id": "AK-177",
    "labelKo": "lower rib pain",
    "category": "msk_neuro_skin",
    "weights": {
      "SLIPPING_RIB": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=근골격/신경/흉벽; related=갈비뼈 미끄럼 증후군; source=#81 갈비뼈 미끄럼 증후군 / 앱 체크리스트 키: lower rib pain; clicking; hooking maneuver"
  },
  {
    "id": "AK-178",
    "labelKo": "movement-related",
    "category": "msk_neuro_skin",
    "weights": {
      "STRAIN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=근골격/신경/흉벽; related=흉벽 근육통 / 근육염좌; source=#45 흉벽 근육통 / 근육염좌 / 앱 체크리스트 키: movement-related; reproducible; trauma/exertion"
  },
  {
    "id": "AK-179",
    "labelKo": "overhead",
    "category": "msk_neuro_skin",
    "weights": {
      "TOS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=근골격/신경/흉벽; related=흉곽출구증후군; source=#52 흉곽출구증후군 / 앱 체크리스트 키: arm symptoms; overhead; vascular signs; duplex/CTA"
  },
  {
    "id": "AK-180",
    "labelKo": "spine imaging",
    "category": "msk_neuro_skin",
    "weights": {
      "THORACIC_COMPRESSION_FX": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=근골격/신경/흉벽; related=흉추 압박골절; source=#80 흉추 압박골절 / 앱 체크리스트 키: elderly/osteoporosis; back tenderness; spine imaging"
  },
  {
    "id": "AK-181",
    "labelKo": "excessive health anxiety",
    "category": "psych_functional",
    "weights": {
      "SOMATIC_CHEST_PAIN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=정신/기능; related=신체증상장애 / 스트레스 관련 흉통; source=#57 신체증상장애 / 스트레스 관련 흉통 / 앱 체크리스트 키: recurrent symptoms; excessive health anxiety; after safe rule-out"
  },
  {
    "id": "AK-182",
    "labelKo": "fear/palpitations",
    "category": "psych_functional",
    "weights": {
      "PANIC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=정신/기능; related=공황발작 / 공황장애; source=#53 공황발작 / 공황장애 / 앱 체크리스트 키: fear/palpitations; hyperventilation; after red flags ruled out"
  },
  {
    "id": "AK-183",
    "labelKo": "hyperventilation",
    "category": "psych_functional",
    "weights": {
      "PANIC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=정신/기능; related=공황발작 / 공황장애; source=#53 공황발작 / 공황장애 / 앱 체크리스트 키: fear/palpitations; hyperventilation; after red flags ruled out"
  },
  {
    "id": "AK-184",
    "labelKo": "CT",
    "category": "history",
    "weights": {
      "PMED": 1,
      "PERF_PUD": 1,
      "GASTRIC_VOLVULUS": 1,
      "STRANGULATED_HERNIA": 1
    },
    "redFlagFor": [
      "PMED",
      "PERF_PUD",
      "GASTRIC_VOLVULUS",
      "STRANGULATED_HERNIA"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=종격동기종 / 기종격; 천공성 소화성 궤양; 위염전 / 위확장; 감돈/교액성 식도열공·횡격막 탈장; source=#27 종격동기종 / 기종격 / 앱 체크리스트 키: subcutaneous emphysema; vomiting/asthma; CT --- #73 천공성 소화성 궤양 / 앱 체크리스트 키: sudden epigastric; peritonitis; free air; CT --- #77 위염전 / 위확장 / 앱 체크리스트 키: severe epigastric/chest; retching; NG failure; CT"
  },
  {
    "id": "AK-185",
    "labelKo": "hypoxia",
    "category": "history",
    "weights": {
      "SICKLE_ACUTE_CHEST": 1,
      "PULM_CONTUSION_FLAIL": 1
    },
    "redFlagFor": [
      "SICKLE_ACUTE_CHEST",
      "PULM_CONTUSION_FLAIL"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=겸상적혈구 급성흉부증후군; 폐좌상 / 동요흉; source=#69 겸상적혈구 급성흉부증후군 / 앱 체크리스트 키: SCD; fever/chest pain; new infiltrate; hypoxia --- #89 폐좌상 / 동요흉 / 앱 체크리스트 키: blunt trauma; hypoxia; CT/CXR; paradoxical movement"
  },
  {
    "id": "AK-186",
    "labelKo": "post-op",
    "category": "history",
    "weights": {
      "MEDIASTINITIS": 1,
      "SUBPHRENIC_ABSCESS": 1
    },
    "redFlagFor": [
      "MEDIASTINITIS",
      "SUBPHRENIC_ABSCESS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=종격동염; 횡격막하 농양 / 간농양; source=#72 종격동염 / 앱 체크리스트 키: esophageal rupture; post-op; fever sepsis; CT mediastinum --- #79 횡격막하 농양 / 간농양 / 앱 체크리스트 키: fever; RUQ/shoulder; post-op; CT/US"
  },
  {
    "id": "AK-187",
    "labelKo": "ECG",
    "category": "history",
    "weights": {
      "STEMI": 1
    },
    "redFlagFor": [
      "STEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=ST분절상승 심근경색; source=#1 ST분절상승 심근경색 / 앱 체크리스트 키: ECG; serial troponin; ACS risk; radiation; diaphoresis"
  },
  {
    "id": "AK-188",
    "labelKo": "ECG dynamic change",
    "category": "history",
    "weights": {
      "NSTEMI": 1
    },
    "redFlagFor": [
      "NSTEMI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=비ST분절상승 심근경색; source=#2 비ST분절상승 심근경색 / 앱 체크리스트 키: serial hs-cTn; ECG dynamic change; GRACE/HEART"
  },
  {
    "id": "AK-189",
    "labelKo": "abrupt tearing",
    "category": "history",
    "weights": {
      "DIS": 1
    },
    "redFlagFor": [
      "DIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=급성 대동맥 박리; source=#8 급성 대동맥 박리 / 앱 체크리스트 키: abrupt tearing; pulse deficit; neuro; CTA aorta"
  },
  {
    "id": "AK-190",
    "labelKo": "biliary dilation",
    "category": "history",
    "weights": {
      "CHOLANG": 1
    },
    "redFlagFor": [
      "CHOLANG"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=담관염; source=#40 담관염 / 앱 체크리스트 키: fever jaundice RUQ; LFT; biliary dilation; drainage"
  },
  {
    "id": "AK-191",
    "labelKo": "diffuse ST/PR",
    "category": "history",
    "weights": {
      "PERI": 1
    },
    "redFlagFor": [
      "PERI"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=심낭염 / 심낭삼출 / 심장압전; source=#10 심낭염 / 심낭삼출 / 심장압전 / 앱 체크리스트 키: pleuritic/positional; rub; diffuse ST/PR; echo"
  },
  {
    "id": "AK-192",
    "labelKo": "drainage",
    "category": "history",
    "weights": {
      "CHOLANG": 1
    },
    "redFlagFor": [
      "CHOLANG"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=담관염; source=#40 담관염 / 앱 체크리스트 키: fever jaundice RUQ; LFT; biliary dilation; drainage"
  },
  {
    "id": "AK-193",
    "labelKo": "esophageal rupture",
    "category": "history",
    "weights": {
      "MEDIASTINITIS": 1
    },
    "redFlagFor": [
      "MEDIASTINITIS"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=종격동염; source=#72 종격동염 / 앱 체크리스트 키: esophageal rupture; post-op; fever sepsis; CT mediastinum"
  },
  {
    "id": "AK-194",
    "labelKo": "free air",
    "category": "history",
    "weights": {
      "PERF_PUD": 1
    },
    "redFlagFor": [
      "PERF_PUD"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=천공성 소화성 궤양; source=#73 천공성 소화성 궤양 / 앱 체크리스트 키: sudden epigastric; peritonitis; free air; CT"
  },
  {
    "id": "AK-195",
    "labelKo": "hypotension",
    "category": "history",
    "weights": {
      "TAMPONADE": 1
    },
    "redFlagFor": [
      "TAMPONADE"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=심장압전 독립 게이트; source=#63 심장압전 독립 게이트 / 앱 체크리스트 키: hypotension; JVD; pulsus; POCUS/echo"
  },
  {
    "id": "AK-196",
    "labelKo": "immediate decompression",
    "category": "history",
    "weights": {
      "TPTX": 1
    },
    "redFlagFor": [
      "TPTX"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=긴장성 기흉; source=#20 긴장성 기흉 / 앱 체크리스트 키: unilateral breath sound; shock; immediate decompression"
  },
  {
    "id": "AK-197",
    "labelKo": "new infiltrate",
    "category": "history",
    "weights": {
      "SICKLE_ACUTE_CHEST": 1
    },
    "redFlagFor": [
      "SICKLE_ACUTE_CHEST"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=겸상적혈구 급성흉부증후군; source=#69 겸상적혈구 급성흉부증후군 / 앱 체크리스트 키: SCD; fever/chest pain; new infiltrate; hypoxia"
  },
  {
    "id": "AK-198",
    "labelKo": "new/worsening/rest angina",
    "category": "history",
    "weights": {
      "UA": 1
    },
    "redFlagFor": [
      "UA"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=불안정 협심증 / ACS; source=#3 불안정 협심증 / ACS / 앱 체크리스트 키: new/worsening/rest angina; serial ECG/troponin"
  },
  {
    "id": "AK-199",
    "labelKo": "widened mediastinum",
    "category": "history",
    "weights": {
      "TRAUMATIC_AORTIC_INJURY": 1
    },
    "redFlagFor": [
      "TRAUMATIC_AORTIC_INJURY"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=외상성 대혈관 손상; source=#88 외상성 대혈관 손상 / 앱 체크리스트 키: high-energy trauma; widened mediastinum; CTA"
  },
  {
    "id": "AK-200",
    "labelKo": "young female ACS",
    "category": "history",
    "weights": {
      "SCAD": 1
    },
    "redFlagFor": [
      "SCAD"
    ],
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=자발성 관상동맥 박리; source=#7 자발성 관상동맥 박리 / 앱 체크리스트 키: young female ACS; postpartum; FMD; angiography"
  },
  {
    "id": "AK-201",
    "labelKo": "US",
    "category": "history",
    "weights": {
      "PLEFF": 1,
      "CHOLE": 1,
      "EMP": 1,
      "MASTITIS_MONDOR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=흉막삼출; 급성 담낭염; 농흉 / 흉막감염; 유방/흉벽 감염 또는 Mondor disease; source=#25 흉막삼출 / 앱 체크리스트 키: dullness; decreased breath sound; US; thoracentesis --- #39 급성 담낭염 / 앱 체크리스트 키: RUQ pain; Murphy; fever; US; Tokyo criteria --- #66 농흉 / 흉막감염 / 앱 체크리스트 키: fever pneumonia; effusion; pleural pH/glucose; US"
  },
  {
    "id": "AK-202",
    "labelKo": "effusion",
    "category": "history",
    "weights": {
      "EMP": 1,
      "TB_PLEURITIS": 1,
      "AUTOIMMUNE_SEROSITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=농흉 / 흉막감염; 결핵성 흉막염 / 폐결핵; 자가면역성 장막염; source=#66 농흉 / 흉막감염 / 앱 체크리스트 키: fever pneumonia; effusion; pleural pH/glucose; US --- #68 결핵성 흉막염 / 폐결핵 / 앱 체크리스트 키: weight loss/night sweat; TB exposure; effusion; AFB/ADA --- #85 자가면역성 장막염 / 앱 체크리스트 키: SLE/RA; pleuritic/positional; effusion; labs"
  },
  {
    "id": "AK-203",
    "labelKo": "after rule-out",
    "category": "history",
    "weights": {
      "ANX": 1,
      "HVS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=불안장애 관련 흉통; 과호흡증후군; source=#54 불안장애 관련 흉통 / 앱 체크리스트 키: stress association; after rule-out --- #55 과호흡증후군 / 앱 체크리스트 키: tachypnea; paresthesia; VBG; after rule-out"
  },
  {
    "id": "AK-204",
    "labelKo": "alarm symptoms",
    "category": "history",
    "weights": {
      "GERD": 1,
      "DYSPEP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=위식도역류질환; 위염 / 기능성 소화불량; source=#31 위식도역류질환 / 앱 체크리스트 키: heartburn; regurgitation; meal/lying; alarm symptoms --- #37 위염 / 기능성 소화불량 / 앱 체크리스트 키: epigastric; alarm symptoms; H pylori/EGD"
  },
  {
    "id": "AK-205",
    "labelKo": "young exertional",
    "category": "history",
    "weights": {
      "HCM": 1,
      "ANOMALOUS_CORONARY": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=비후성 심근병증; 선천성 관상동맥 이상 / 심근교; source=#15 비후성 심근병증 / 앱 체크리스트 키: young exertional; syncope; family sudden death; echo/CMR --- #65 선천성 관상동맥 이상 / 심근교 / 앱 체크리스트 키: young exertional; syncope; CCTA coronary anatomy"
  },
  {
    "id": "AK-206",
    "labelKo": "ACS rule-out",
    "category": "history",
    "weights": {
      "TTS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=스트레스성 심근병증; source=#17 스트레스성 심근병증 / 앱 체크리스트 키: stress trigger; postmenopausal; echo apical ballooning; ACS rule-out"
  },
  {
    "id": "AK-207",
    "labelKo": "AF/IE",
    "category": "history",
    "weights": {
      "SPLENIC_INFARCT": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=비장경색; source=#78 비장경색 / 앱 체크리스트 키: LUQ/left chest; AF/IE; CT abdomen"
  },
  {
    "id": "AK-208",
    "labelKo": "AF/valve/IE",
    "category": "history",
    "weights": {
      "CORONARY_EMBOLISM": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=관상동맥 색전/혈전증; source=#60 관상동맥 색전/혈전증 / 앱 체크리스트 키: AF/valve/IE; ACS with low CAD risk; echo/TEE"
  },
  {
    "id": "AK-209",
    "labelKo": "CFR/IMR",
    "category": "history",
    "weights": {
      "INOCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=미세혈관 협심증; source=#6 미세혈관 협심증 / 앱 체크리스트 키: normal coronaries but angina; stress perfusion; CFR/IMR"
  },
  {
    "id": "AK-210",
    "labelKo": "CT/US",
    "category": "history",
    "weights": {
      "SUBPHRENIC_ABSCESS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=횡격막하 농양 / 간농양; source=#79 횡격막하 농양 / 간농양 / 앱 체크리스트 키: fever; RUQ/shoulder; post-op; CT/US"
  },
  {
    "id": "AK-211",
    "labelKo": "CT/biopsy",
    "category": "history",
    "weights": {
      "LUNGCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=폐암 / 흉막종양; source=#30 폐암 / 흉막종양 / 앱 체크리스트 키: smoking; weight loss; hemoptysis; CT/biopsy"
  },
  {
    "id": "AK-212",
    "labelKo": "ECG monitor",
    "category": "history",
    "weights": {
      "ARR": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=부정맥 관련 흉통; source=#16 부정맥 관련 흉통 / 앱 체크리스트 키: palpitation; syncope; ECG monitor; electrolytes"
  },
  {
    "id": "AK-213",
    "labelKo": "LUQ/left chest",
    "category": "history",
    "weights": {
      "SPLENIC_INFARCT": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=비장경색; source=#78 비장경색 / 앱 체크리스트 키: LUQ/left chest; AF/IE; CT abdomen"
  },
  {
    "id": "AK-214",
    "labelKo": "MI + nonobstructive coronaries",
    "category": "history",
    "weights": {
      "MINOCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=MINOCA; source=#62 MINOCA / 앱 체크리스트 키: MI + nonobstructive coronaries; CMR/OCT"
  },
  {
    "id": "AK-215",
    "labelKo": "NG failure",
    "category": "history",
    "weights": {
      "GASTRIC_VOLVULUS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=위염전 / 위확장; source=#77 위염전 / 위확장 / 앱 체크리스트 키: severe epigastric/chest; retching; NG failure; CT"
  },
  {
    "id": "AK-216",
    "labelKo": "PE symptoms",
    "category": "history",
    "weights": {
      "PULM_INFARCT": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=폐경색; source=#26 폐경색 / 앱 체크리스트 키: PE symptoms; hemoptysis; wedge opacity; CTPA"
  },
  {
    "id": "AK-217",
    "labelKo": "PEF",
    "category": "history",
    "weights": {
      "ASTHMA_EXAC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=천식 급성 악화; source=#28 천식 급성 악화 / 앱 체크리스트 키: wheeze; PEF; response to bronchodilator"
  },
  {
    "id": "AK-218",
    "labelKo": "RV signs",
    "category": "history",
    "weights": {
      "PH_RV_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=폐고혈압 / 우심실 허혈; source=#64 폐고혈압 / 우심실 허혈 / 앱 체크리스트 키: exertional syncope; RV signs; echo/RHC"
  },
  {
    "id": "AK-219",
    "labelKo": "SLE/RA",
    "category": "history",
    "weights": {
      "AUTOIMMUNE_SEROSITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=자가면역성 장막염; source=#85 자가면역성 장막염 / 앱 체크리스트 키: SLE/RA; pleuritic/positional; effusion; labs"
  },
  {
    "id": "AK-220",
    "labelKo": "TB exposure",
    "category": "history",
    "weights": {
      "TB_PLEURITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=결핵성 흉막염 / 폐결핵; source=#68 결핵성 흉막염 / 폐결핵 / 앱 체크리스트 키: weight loss/night sweat; TB exposure; effusion; AFB/ADA"
  },
  {
    "id": "AK-221",
    "labelKo": "after red flags ruled out",
    "category": "history",
    "weights": {
      "PANIC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=공황발작 / 공황장애; source=#53 공황발작 / 공황장애 / 앱 체크리스트 키: fear/palpitations; hyperventilation; after red flags ruled out"
  },
  {
    "id": "AK-222",
    "labelKo": "after safe rule-out",
    "category": "history",
    "weights": {
      "SOMATIC_CHEST_PAIN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=신체증상장애 / 스트레스 관련 흉통; source=#57 신체증상장애 / 스트레스 관련 흉통 / 앱 체크리스트 키: recurrent symptoms; excessive health anxiety; after safe rule-out"
  },
  {
    "id": "AK-223",
    "labelKo": "arm symptoms",
    "category": "history",
    "weights": {
      "TOS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=흉곽출구증후군; source=#52 흉곽출구증후군 / 앱 체크리스트 키: arm symptoms; overhead; vascular signs; duplex/CTA"
  },
  {
    "id": "AK-224",
    "labelKo": "arrhythmia",
    "category": "history",
    "weights": {
      "MYO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=심근염; source=#11 심근염 / 앱 체크리스트 키: viral prodrome; troponin; arrhythmia; echo/CMR"
  },
  {
    "id": "AK-225",
    "labelKo": "brief sharp",
    "category": "history",
    "weights": {
      "PRECORDIAL_CATCH": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=전흉부 포착 증후군; source=#84 전흉부 포착 증후군 / 앱 체크리스트 키: young; brief sharp; no exertional red flags"
  },
  {
    "id": "AK-226",
    "labelKo": "dullness",
    "category": "history",
    "weights": {
      "PLEFF": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=흉막삼출; source=#25 흉막삼출 / 앱 체크리스트 키: dullness; decreased breath sound; US; thoracentesis"
  },
  {
    "id": "AK-227",
    "labelKo": "elderly/osteoporosis",
    "category": "history",
    "weights": {
      "THORACIC_COMPRESSION_FX": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=흉추 압박골절; source=#80 흉추 압박골절 / 앱 체크리스트 키: elderly/osteoporosis; back tenderness; spine imaging"
  },
  {
    "id": "AK-228",
    "labelKo": "exertional",
    "category": "history",
    "weights": {
      "SA_CCD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=안정형 협심증; source=#4 안정형 협심증 / 앱 체크리스트 키: exertional; rest relief; CCTA/stress test"
  },
  {
    "id": "AK-229",
    "labelKo": "exposure",
    "category": "history",
    "weights": {
      "VIRAL_PNA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=바이러스 폐렴 / COVID-19 / 인플루엔자; source=#70 바이러스 폐렴 / COVID-19 / 인플루엔자 / 앱 체크리스트 키: viral syndrome; exposure; PCR; CXR"
  },
  {
    "id": "AK-230",
    "labelKo": "fatigue",
    "category": "history",
    "weights": {
      "FIBRO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=섬유근통; source=#51 섬유근통 / 앱 체크리스트 키: chronic widespread pain; fatigue; sleep"
  },
  {
    "id": "AK-231",
    "labelKo": "immunosuppression",
    "category": "history",
    "weights": {
      "ZOSTER": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=대상포진; source=#50 대상포진 / 앱 체크리스트 키: dermatomal pain; vesicles; immunosuppression"
  },
  {
    "id": "AK-232",
    "labelKo": "labs",
    "category": "history",
    "weights": {
      "AUTOIMMUNE_SEROSITIS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=자가면역성 장막염; source=#85 자가면역성 장막염 / 앱 체크리스트 키: SLE/RA; pleuritic/positional; effusion; labs"
  },
  {
    "id": "AK-233",
    "labelKo": "meal/lying",
    "category": "history",
    "weights": {
      "GERD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=위식도역류질환; source=#31 위식도역류질환 / 앱 체크리스트 키: heartburn; regurgitation; meal/lying; alarm symptoms"
  },
  {
    "id": "AK-234",
    "labelKo": "movement",
    "category": "history",
    "weights": {
      "COSTO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=늑연골염; source=#43 늑연골염 / 앱 체크리스트 키: reproducible tenderness; movement; no red flag"
  },
  {
    "id": "AK-235",
    "labelKo": "multiple patients",
    "category": "history",
    "weights": {
      "CO_POISONING_ISCHEMIA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=일산화탄소 중독 관련 심근허혈; source=#86 일산화탄소 중독 관련 심근허혈 / 앱 체크리스트 키: CO exposure; headache; multiple patients; COHb/troponin"
  },
  {
    "id": "AK-236",
    "labelKo": "neck/back movement",
    "category": "history",
    "weights": {
      "CRAD_TRAD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=경추 또는 흉추 신경근병증; source=#49 경추 또는 흉추 신경근병증 / 앱 체크리스트 키: neck/back movement; neuro deficit; MRI"
  },
  {
    "id": "AK-237",
    "labelKo": "nitrate response",
    "category": "history",
    "weights": {
      "VSA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=관상동맥 연축 / 변이형 협심증; source=#5 관상동맥 연축 / 변이형 협심증 / 앱 체크리스트 키: rest/night pain; transient ST; nitrate response; stimulant"
  },
  {
    "id": "AK-238",
    "labelKo": "no exertional red flags",
    "category": "history",
    "weights": {
      "PRECORDIAL_CATCH": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=전흉부 포착 증후군; source=#84 전흉부 포착 증후군 / 앱 체크리스트 키: young; brief sharp; no exertional red flags"
  },
  {
    "id": "AK-239",
    "labelKo": "no red flag",
    "category": "history",
    "weights": {
      "COSTO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=늑연골염; source=#43 늑연골염 / 앱 체크리스트 키: reproducible tenderness; movement; no red flag"
  },
  {
    "id": "AK-240",
    "labelKo": "noncardiac recurrent",
    "category": "history",
    "weights": {
      "FCP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=기능성 흉통; source=#56 기능성 흉통 / 앱 체크리스트 키: noncardiac recurrent; normal workup; Rome"
  },
  {
    "id": "AK-241",
    "labelKo": "normal coronaries but angina",
    "category": "history",
    "weights": {
      "INOCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=미세혈관 협심증; source=#6 미세혈관 협심증 / 앱 체크리스트 키: normal coronaries but angina; stress perfusion; CFR/IMR"
  },
  {
    "id": "AK-242",
    "labelKo": "normal workup",
    "category": "history",
    "weights": {
      "FCP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=기능성 흉통; source=#56 기능성 흉통 / 앱 체크리스트 키: noncardiac recurrent; normal workup; Rome"
  },
  {
    "id": "AK-243",
    "labelKo": "organ damage",
    "category": "history",
    "weights": {
      "HTN_EMERG": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=고혈압 응급증 관련 흉통; source=#18 고혈압 응급증 관련 흉통 / 앱 체크리스트 키: severe BP; organ damage; ECG/troponin/renal/neuro"
  },
  {
    "id": "AK-244",
    "labelKo": "pleural pH/glucose",
    "category": "history",
    "weights": {
      "EMP": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=농흉 / 흉막감염; source=#66 농흉 / 흉막감염 / 앱 체크리스트 키: fever pneumonia; effusion; pleural pH/glucose; US"
  },
  {
    "id": "AK-245",
    "labelKo": "postmenopausal",
    "category": "history",
    "weights": {
      "TTS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=스트레스성 심근병증; source=#17 스트레스성 심근병증 / 앱 체크리스트 키: stress trigger; postmenopausal; echo apical ballooning; ACS rule-out"
  },
  {
    "id": "AK-246",
    "labelKo": "postprandial",
    "category": "history",
    "weights": {
      "HH": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=열공탈장; source=#42 열공탈장 / 앱 체크리스트 키: postprandial; reflux; dysphagia; CT/barium/EGD"
  },
  {
    "id": "AK-247",
    "labelKo": "recurrent symptoms",
    "category": "history",
    "weights": {
      "SOMATIC_CHEST_PAIN": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=신체증상장애 / 스트레스 관련 흉통; source=#57 신체증상장애 / 스트레스 관련 흉통 / 앱 체크리스트 키: recurrent symptoms; excessive health anxiety; after safe rule-out"
  },
  {
    "id": "AK-248",
    "labelKo": "reflux",
    "category": "history",
    "weights": {
      "HH": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=열공탈장; source=#42 열공탈장 / 앱 체크리스트 키: postprandial; reflux; dysphagia; CT/barium/EGD"
  },
  {
    "id": "AK-249",
    "labelKo": "response to bronchodilator",
    "category": "history",
    "weights": {
      "ASTHMA_EXAC": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=천식 급성 악화; source=#28 천식 급성 악화 / 앱 체크리스트 키: wheeze; PEF; response to bronchodilator"
  },
  {
    "id": "AK-250",
    "labelKo": "rest relief",
    "category": "history",
    "weights": {
      "SA_CCD": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=안정형 협심증; source=#4 안정형 협심증 / 앱 체크리스트 키: exertional; rest relief; CCTA/stress test"
  },
  {
    "id": "AK-251",
    "labelKo": "retching",
    "category": "history",
    "weights": {
      "GASTRIC_VOLVULUS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=위염전 / 위확장; source=#77 위염전 / 위확장 / 앱 체크리스트 키: severe epigastric/chest; retching; NG failure; CT"
  },
  {
    "id": "AK-252",
    "labelKo": "sleep",
    "category": "history",
    "weights": {
      "FIBRO": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=섬유근통; source=#51 섬유근통 / 앱 체크리스트 키: chronic widespread pain; fatigue; sleep"
  },
  {
    "id": "AK-253",
    "labelKo": "stress association",
    "category": "history",
    "weights": {
      "ANX": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=불안장애 관련 흉통; source=#54 불안장애 관련 흉통 / 앱 체크리스트 키: stress association; after rule-out"
  },
  {
    "id": "AK-254",
    "labelKo": "stress perfusion",
    "category": "history",
    "weights": {
      "INOCA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=미세혈관 협심증; source=#6 미세혈관 협심증 / 앱 체크리스트 키: normal coronaries but angina; stress perfusion; CFR/IMR"
  },
  {
    "id": "AK-255",
    "labelKo": "stress trigger",
    "category": "history",
    "weights": {
      "TTS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=스트레스성 심근병증; source=#17 스트레스성 심근병증 / 앱 체크리스트 키: stress trigger; postmenopausal; echo apical ballooning; ACS rule-out"
  },
  {
    "id": "AK-256",
    "labelKo": "sudden unilateral",
    "category": "history",
    "weights": {
      "PTX": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=자연기흉; source=#21 자연기흉 / 앱 체크리스트 키: sudden unilateral; tall thin/smoking; CXR/US"
  },
  {
    "id": "AK-257",
    "labelKo": "temperature trigger",
    "category": "history",
    "weights": {
      "ESPASM": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=식도경련 / 식도운동장애; source=#33 식도경련 / 식도운동장애 / 앱 체크리스트 키: dysphagia; temperature trigger; manometry"
  },
  {
    "id": "AK-258",
    "labelKo": "thoracentesis",
    "category": "history",
    "weights": {
      "PLEFF": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=흉막삼출; source=#25 흉막삼출 / 앱 체크리스트 키: dullness; decreased breath sound; US; thoracentesis"
  },
  {
    "id": "AK-259",
    "labelKo": "transient ST",
    "category": "history",
    "weights": {
      "VSA": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=관상동맥 연축 / 변이형 협심증; source=#5 관상동맥 연축 / 변이형 협심증 / 앱 체크리스트 키: rest/night pain; transient ST; nitrate response; stimulant"
  },
  {
    "id": "AK-260",
    "labelKo": "vascular signs",
    "category": "history",
    "weights": {
      "TOS": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=흉곽출구증후군; source=#52 흉곽출구증후군 / 앱 체크리스트 키: arm symptoms; overhead; vascular signs; duplex/CTA"
  },
  {
    "id": "AK-261",
    "labelKo": "wedge opacity",
    "category": "history",
    "weights": {
      "PULM_INFARCT": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=폐경색; source=#26 폐경색 / 앱 체크리스트 키: PE symptoms; hemoptysis; wedge opacity; CTPA"
  },
  {
    "id": "AK-262",
    "labelKo": "young",
    "category": "history",
    "weights": {
      "PRECORDIAL_CATCH": 1
    },
    "sourceNote": "v1.2 AppKey checklist. section=기타; related=전흉부 포착 증후군; source=#84 전흉부 포착 증후군 / 앱 체크리스트 키: young; brief sharp; no exertional red flags"
  }
];
