// Generated by scripts/importClinicalXlsx.py from chest pain v1.2 workbooks.
// Do not edit generated arrays by hand; update the source workbook or generator instead.
import type { ClinicalSourceReference } from "@/types/clinical";

export const clinicalSourceReferences: ClinicalSourceReference[] = [
  {
    "key": "ACS2025",
    "title": "2025 ACC/AHA/ACEP/NAEMSP/SCAI Guideline for ACS",
    "url": "https://www.ahajournals.org/doi/10.1161/CIR.0000000000001309",
    "coverage": "ACS, STEMI/NSTEMI/UA, troponin workflow",
    "doiOrFormalUrl": "10.1161/CIR.0000000000001309",
    "year": "2025",
    "evidenceType": "치료중심(진단 보조)"
  },
  {
    "key": "ESC_ACS2023",
    "title": "2023 ESC Guideline for Acute Coronary Syndromes",
    "url": "https://academic.oup.com/eurheartj/article/44/38/3720/7243210",
    "coverage": "ACS diagnosis/risk stratification",
    "doiOrFormalUrl": "10.1093/eurheartj/ehad191",
    "year": "2023",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "ChestPain2021",
    "title": "2021 AHA/ACC Guideline for Evaluation and Diagnosis of Chest Pain",
    "url": "https://www.ahajournals.org/doi/10.1161/CIR.0000000000001029",
    "coverage": "General chest pain workflow, ECG/troponin, risk-based testing",
    "doiOrFormalUrl": "10.1161/CIR.0000000000001029",
    "year": "2021",
    "evidenceType": "진단중심(핵심)"
  },
  {
    "key": "Aortic2022",
    "title": "2022 ACC/AHA Guideline for Aortic Disease",
    "url": "https://www.ahajournals.org/doi/10.1161/CIR.0000000000001106",
    "coverage": "Aortic dissection, aneurysm, acute aortic syndrome",
    "doiOrFormalUrl": "10.1161/CIR.0000000000001106",
    "year": "2022",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "PE2019",
    "title": "2019 ESC Guideline for Acute Pulmonary Embolism",
    "url": "https://academic.oup.com/eurheartj/article/41/4/543/5556136",
    "coverage": "PE pretest probability, D-dimer, CTPA/VQ",
    "doiOrFormalUrl": "10.1093/eurheartj/ehz405",
    "year": "2019",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "BTSPleural2023",
    "title": "British Thoracic Society Guideline for Pleural Disease 2023",
    "url": "https://thorax.bmj.com/content/78/Suppl_3/s1",
    "coverage": "Pneumothorax, pleural effusion, pleural infection",
    "doiOrFormalUrl": "10.1136/thorax-2023-220304",
    "year": "2023",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "CAP2019",
    "title": "ATS/IDSA Community-Acquired Pneumonia Guideline",
    "url": "https://www.atsjournals.org/doi/10.1164/rccm.201908-1581ST",
    "coverage": "Pneumonia diagnostic and management framework",
    "doiOrFormalUrl": "10.1164/rccm.201908-1581ST",
    "year": "2019",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "GERD2022",
    "title": "ACG Guideline for GERD",
    "url": "https://journals.lww.com/ajg/fulltext/2022/01000/acg_clinical_guideline_for_the_diagnosis_and.14.aspx",
    "coverage": "GERD, noncardiac chest pain, PPI/EGD/pH",
    "doiOrFormalUrl": "10.14309/ajg.0000000000001538",
    "year": "2022",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "Pancreatitis2024",
    "title": "ACG Acute Pancreatitis Guideline 2024",
    "url": "https://doi.org/10.14309/ajg.0000000000002645",
    "coverage": "Acute pancreatitis diagnosis and imaging use",
    "doiOrFormalUrl": "10.14309/ajg.0000000000002645",
    "year": "2024",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "WSES_PUD2019",
    "title": "WSES Guideline for Perforated/Bleeding Peptic Ulcer",
    "url": "https://wjes.biomedcentral.com/articles/10.1186/s13017-019-0283-9",
    "coverage": "Perforated peptic ulcer emergency pathway",
    "doiOrFormalUrl": "10.1186/s13017-019-0283-9",
    "year": "2019",
    "evidenceType": "치료중심(외과)"
  },
  {
    "key": "Tokyo2018",
    "title": "Tokyo Guidelines 2018",
    "url": "https://www.jshbps.jp/modules/en/index.php?content_id=47",
    "coverage": "Acute cholecystitis/cholangitis criteria and severity",
    "doiOrFormalUrl": "TG18 (J Hepatobiliary Pancreat Sci 2018)",
    "year": "2018",
    "evidenceType": "혼합(진단기준+중증도)"
  },
  {
    "key": "CCS2024",
    "title": "2024 ESC Guideline for Chronic Coronary Syndromes",
    "url": "https://academic.oup.com/eurheartj/article/45/36/3415/7754075",
    "coverage": "Stable angina, vasospastic/microvascular angina",
    "doiOrFormalUrl": "10.1093/eurheartj/ehae177",
    "year": "2024",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "Cardiomyopathy2023",
    "title": "2023 ESC Guideline for Cardiomyopathies",
    "url": "https://academic.oup.com/eurheartj/article/44/37/3503/7246608",
    "coverage": "HCM and cardiomyopathy diagnostic evaluation",
    "doiOrFormalUrl": "10.1093/eurheartj/ehad194",
    "year": "2023",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "VHD2025",
    "title": "2025 ESC/EACTS Valvular Heart Disease Guideline",
    "url": "https://academic.oup.com/eurheartj/article/46/44/4635/8234488",
    "coverage": "Aortic stenosis/MVP/valvular disease",
    "doiOrFormalUrl": "10.1093/eurheartj/ehaf194",
    "year": "2025",
    "evidenceType": "치료중심(진단기준 포함)"
  },
  {
    "key": "SCAD2018",
    "title": "AHA Scientific Statement on SCAD",
    "url": "https://www.ahajournals.org/doi/10.1161/CIR.0000000000000564",
    "coverage": "SCAD recognition and diagnostic pathway",
    "doiOrFormalUrl": "10.1161/CIR.0000000000000564",
    "year": "2018",
    "evidenceType": "혼합(인지+진단)"
  },
  {
    "key": "MyoPeri2025",
    "title": "2025 ESC Guideline for Myocarditis and Pericarditis",
    "url": "https://academic.oup.com/eurheartj/article/46/40/3952/8234483",
    "coverage": "Myocarditis/pericarditis/tamponade",
    "doiOrFormalUrl": "10.1093/eurheartj/ehaf192",
    "year": "2025",
    "evidenceType": "혼합(진단+치료); IMPS"
  },
  {
    "key": "ACC_Myocarditis2024",
    "title": "2024 ACC Expert Consensus Decision Pathway on Myocarditis",
    "url": "https://www.jacc.org/doi/10.1016/j.jacc.2024.09.002",
    "coverage": "Myocarditis suspicion, CMR, pitfalls",
    "doiOrFormalUrl": "ACC ECDP 2024 (JACC)",
    "year": "2024",
    "evidenceType": "진단중심(ECDP)"
  },
  {
    "key": "UniversalMI2018",
    "title": "Fourth Universal Definition of Myocardial Infarction",
    "url": "https://www.ahajournals.org/doi/10.1161/CIR.0000000000000617",
    "coverage": "Type 1/2 MI, myocardial injury definitions",
    "doiOrFormalUrl": "10.1161/CIR.0000000000000617",
    "year": "2018",
    "evidenceType": "정의/분류(Type1·2 MI)"
  },
  {
    "key": "WSES_Esoph2019",
    "title": "WSES Guideline for Esophageal Emergencies",
    "url": "https://wjes.biomedcentral.com/articles/10.1186/s13017-019-0245-2",
    "coverage": "Esophageal rupture, mediastinitis, CT/contrast imaging",
    "doiOrFormalUrl": "10.1186/s13017-019-0245-2",
    "year": "2019",
    "evidenceType": "혼합(진단+치료)"
  },
  {
    "key": "MSDChestPain2024",
    "title": "MSD Manual Professional: Chest Pain",
    "url": "https://www.msdmanuals.com/professional/cardiovascular-disorders/symptoms-of-cardiovascular-disorders/chest-pain",
    "coverage": "Broad differential and basic evaluation",
    "doiOrFormalUrl": "MSD Manual Professional",
    "year": "2024",
    "evidenceType": "참고서(교과서)"
  },
  {
    "key": "MSDTensionPTX",
    "title": "MSD Manual Professional: Tension Pneumothorax",
    "url": "https://www.msdmanuals.com/professional/injuries-poisoning/thoracic-trauma/tension-pneumothorax",
    "coverage": "Clinical diagnosis and immediate decompression",
    "doiOrFormalUrl": "MSD Manual Professional",
    "year": "—",
    "evidenceType": "참고서(교과서)"
  },
  {
    "key": "ChestPainECDP2022",
    "title": "2022 ACC Expert Consensus Decision Pathway: ED 흉통 평가·처분",
    "url": "https://www.jacc.org/doi/10.1016/j.jacc.2022.08.750",
    "coverage": "ED 저/중/고위험 처분, HEART/EDACS, hs-cTn CDP",
    "doiOrFormalUrl": "10.1016/j.jacc.2022.08.750",
    "year": "2022",
    "evidenceType": "진단중심(처분 CDP)"
  }
];
